# Generated by Django 6.0.8 on 2026-09-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organizationcapability",
            constraint=models.CheckConstraint(
                condition=models.Q(("capability__in", ["buyer", "supplier", "broker"])),
                name="check_valid_capability",
            ),
        ),
    ]
