# Generated by Django 6.0.8 on 2026-09-09 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationcapability_check_valid_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["owner", "manager", "member", "viewer"])
                ),
                name="check_valid_membership_role",
            ),
        ),
    ]
