# Generated by Django 6.0.8 on 2026-09-17 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('organizations', '0004_organizationcommodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOperatingArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(help_text='Geographic area where the organization operates.', on_delete=django.db.models.deletion.CASCADE, related_name='operating_organizations', to='geography.geographicarea')),
                ('organization', models.ForeignKey(help_text='Organization declaring operational coverage in this area.', on_delete=django.db.models.deletion.CASCADE, related_name='operating_areas', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'area'), name='unique_organization_operating_area')],
            },
        ),
    ]
