# Generated by Django 6.0.8 on 2026-09-17 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Canonical, stable, machine-readable area code (e.g. 'IR', 'IR-07', 'IR-07-THR').", max_length=50, unique=True)),
                ('area_type', models.CharField(choices=[('COUNTRY', 'Country'), ('ADMINISTRATIVE_AREA', 'Administrative Area'), ('CITY', 'City')], help_text='Exact structural type: COUNTRY, ADMINISTRATIVE_AREA, or CITY.', max_length=30)),
                ('country_code', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'IR').", max_length=2)),
                ('name_fa', models.CharField(help_text='Persian display name.', max_length=100)),
                ('name_en', models.CharField(help_text='English display name.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this area is active for selection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent geographic area in the hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geography.geographicarea')),
            ],
            options={
                'ordering': ['country_code', 'area_type', 'code'],
                'indexes': [models.Index(fields=['country_code', 'area_type'], name='idx_geo_country_type'), models.Index(fields=['parent', 'area_type'], name='idx_geo_parent_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('area_type', 'COUNTRY')), models.Q(('parent__isnull', False), ('area_type__in', ['ADMINISTRATIVE_AREA', 'CITY'])), _connector='OR'), name='check_geographic_area_parent_nullability'), models.CheckConstraint(condition=models.Q(('area_type__in', ['COUNTRY', 'ADMINISTRATIVE_AREA', 'CITY'])), name='check_valid_geographic_area_type')],
            },
        ),
    ]
