# Generated by Django 6.0.8 on 2026-09-17 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0009_opportunity_supply_conversion'),
        ('organizations', '0004_organizationcommodity'),
        ('trade_hub', '0003_supplylisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Canonical unique code identifying this policy (e.g. 'default-commodity-matching').", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable policy name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the matching policy objectives and scope.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='idx_matching_policy_code')],
            },
        ),
        migrations.CreateModel(
            name='MatchingPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing version number (must be > 0).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', help_text='Current lifecycle state of this policy version.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Release notes or rationale for this policy version.')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Deterministic configuration snapshot of weights, thresholds, and rule parameters.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='Owning matching policy.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='matching.matchingpolicy')),
            ],
            options={
                'ordering': ['policy', '-version'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_version', models.PositiveIntegerField(help_text='Exact RFQ aggregate version at execution time.')),
                ('audience', models.CharField(choices=[('BUYER', 'Buyer'), ('OPERATOR', 'Operator')], help_text='Target audience scope (BUYER or OPERATOR).', max_length=20)),
                ('engine_version', models.CharField(default='matching-engine-v1', help_text='Centralized semantic matching engine contract version.', max_length=50)),
                ('target_snapshot', models.JSONField(blank=True, default=dict, help_text='Canonical snapshot of RFQ demand at execution time.')),
                ('input_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 fingerprint of the canonical matching inputs.', max_length=64)),
                ('result_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 fingerprint of the canonical matching results.', max_length=64)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the matching run was generated.')),
                ('policy_version', models.ForeignKey(help_text='Published policy version used for candidate evaluation.', on_delete=django.db.models.deletion.PROTECT, related_name='matching_runs', to='matching.matchingpolicyversion')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Authenticated user who initiated the run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_matching_runs', to=settings.AUTH_USER_MODEL)),
                ('requesting_organization', models.ForeignKey(blank=True, help_text='Buyer organization that requested the run. Null for platform Operator/Admin actors.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_runs', to='organizations.organization')),
                ('rfq', models.ForeignKey(help_text='Target RFQ procurement demand.', on_delete=django.db.models.deletion.PROTECT, related_name='matching_runs', to='trade_hub.rfq')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane', models.CharField(choices=[('DIRECT_SUPPLY', 'Direct Supply'), ('POTENTIAL_SUPPLIER', 'Potential Supplier'), ('BROKER_PATH', 'Broker Path')], help_text='Lane to which this candidate belongs (Direct Supply, Potential Supplier, Broker Path).', max_length=30)),
                ('candidate_kind', models.CharField(choices=[('SUPPLY_LISTING', 'Supply Listing'), ('SUPPLY_OPPORTUNITY', 'Supply Opportunity'), ('SUPPLIER_ORGANIZATION', 'Supplier Organization'), ('BROKER_ORGANIZATION', 'Broker Organization')], help_text='Candidate evidence type.', max_length=30)),
                ('candidate_snapshot', models.JSONField(blank=True, default=dict, help_text='Audience-scoped frozen snapshot of candidate evidence data.')),
                ('eligible', models.BooleanField(default=True, help_text='Whether candidate passed all hard eligibility gates.')),
                ('exclusion_code', models.CharField(blank=True, default='', help_text='Machine-readable code identifying why candidate was excluded.', max_length=100)),
                ('fit_score', models.DecimalField(blank=True, decimal_places=2, help_text='Specification / capability fit percentage (0.00 - 100.00).', max_digits=6, null=True)),
                ('evidence_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Known evidence coverage percentage (0.00 - 100.00).', max_digits=6, null=True)),
                ('ranking_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final composite ranking score percentage (0.00 - 100.00).', max_digits=6, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, help_text="Rank within the candidate's lane (1-based, rank > 0).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_organization', models.ForeignKey(blank=True, help_text='Source Broker Organization (BROKER_PATH lane).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_matching_candidates', to='organizations.organization')),
                ('supplier_organization', models.ForeignKey(blank=True, help_text='Source Supplier Organization (POTENTIAL_SUPPLIER lane).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_matching_candidates', to='organizations.organization')),
                ('supply_listing', models.ForeignKey(blank=True, help_text='Source Supply Listing (DIRECT_SUPPLY lane).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_candidates', to='trade_hub.supplylisting')),
                ('supply_opportunity', models.ForeignKey(blank=True, help_text='Source Qualified Supply Opportunity (DIRECT_SUPPLY lane, Operator only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_candidates', to='opportunities.opportunity')),
                ('run', models.ForeignKey(help_text='Associated matching execution run.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='matching.matchingrun')),
            ],
            options={
                'ordering': ['run', 'lane', 'rank', '-ranking_score'],
            },
        ),
        migrations.CreateModel(
            name='MatchingSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('SPECIFICATION', 'Specification'), ('QUANTITY', 'Quantity'), ('AVAILABILITY', 'Availability'), ('GEOGRAPHY', 'Geography'), ('TRUST', 'Trust'), ('HISTORY', 'History')], help_text='Evaluation dimension (Specification, Quantity, Availability, Geography, Trust, History).', max_length=50)),
                ('code', models.CharField(help_text="Machine-readable rule or attribute code (e.g. 'spec.penetration_grade', 'availability').", max_length=100)),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('PARTIAL', 'Partial'), ('FAIL', 'Fail'), ('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Structured outcome: PASS, PARTIAL, FAIL, UNKNOWN, NOT_APPLICABLE.', max_length=20)),
                ('is_hard', models.BooleanField(default=False, help_text='Whether this signal evaluated a hard eligibility gate.')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Dimension or rule weight (>= 0).', max_digits=6, null=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized score in [0.0000, 1.0000] for known evaluation. Null for UNKNOWN/NOT_APPLICABLE.', max_digits=5, null=True)),
                ('contribution', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted contribution towards candidate score (>= 0).', max_digits=6, null=True)),
                ('expected_value', models.JSONField(blank=True, default=dict, help_text='Constrained structured JSONB representing target demand expectation.', null=True)),
                ('actual_value', models.JSONField(blank=True, default=dict, help_text='Constrained structured JSONB representing candidate actual supply evidence.', null=True)),
                ('reason_code', models.CharField(blank=True, default='', help_text='Machine-readable outcome explanation code (never localized text).', max_length=100)),
                ('semantic_identity', models.CharField(blank=True, help_text='Optional stable UUID or fingerprint snapshot of commodity attribute semantic identity.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(help_text='Candidate evaluated by this signal.', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='matching.matchingcandidate')),
            ],
            options={
                'ordering': ['candidate', 'dimension', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='matchingpolicyversion',
            index=models.Index(fields=['policy', 'version'], name='idx_match_pol_ver'),
        ),
        migrations.AddIndex(
            model_name='matchingpolicyversion',
            index=models.Index(fields=['status'], name='idx_match_pol_status'),
        ),
        migrations.AddConstraint(
            model_name='matchingpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='check_positive_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='matchingpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'RETIRED'])), name='check_valid_policy_version_status'),
        ),
        migrations.AddConstraint(
            model_name='matchingpolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_policy_version'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['rfq', '-generated_at'], name='idx_match_run_rfq_gen'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['audience'], name='idx_match_run_audience'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['policy_version'], name='idx_match_run_policy_ver'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['input_fingerprint'], name='idx_match_run_inp_fp'),
        ),
        migrations.AddConstraint(
            model_name='matchingrun',
            constraint=models.CheckConstraint(condition=models.Q(('rfq_version__gte', 1)), name='check_positive_matching_run_rfq_version'),
        ),
        migrations.AddConstraint(
            model_name='matchingrun',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['BUYER', 'OPERATOR'])), name='check_valid_matching_run_audience'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['run', 'lane'], name='idx_match_cand_run_lane'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['candidate_kind'], name='idx_match_cand_kind'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['eligible'], name='idx_match_cand_eligible'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supply_listing__isnull', False), ('supply_opportunity__isnull', True), ('supplier_organization__isnull', True), ('broker_organization__isnull', True)), models.Q(('supply_listing__isnull', True), ('supply_opportunity__isnull', False), ('supplier_organization__isnull', True), ('broker_organization__isnull', True)), models.Q(('supply_listing__isnull', True), ('supply_opportunity__isnull', True), ('supplier_organization__isnull', False), ('broker_organization__isnull', True)), models.Q(('supply_listing__isnull', True), ('supply_opportunity__isnull', True), ('supplier_organization__isnull', True), ('broker_organization__isnull', False)), _connector='OR'), name='check_candidate_source_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate_kind', 'SUPPLY_LISTING'), ('supply_listing__isnull', False)), models.Q(('candidate_kind', 'SUPPLY_OPPORTUNITY'), ('supply_opportunity__isnull', False)), models.Q(('candidate_kind', 'SUPPLIER_ORGANIZATION'), ('supplier_organization__isnull', False)), models.Q(('candidate_kind', 'BROKER_ORGANIZATION'), ('broker_organization__isnull', False)), _connector='OR'), name='check_candidate_kind_source_consistency'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lane', 'DIRECT_SUPPLY'), models.Q(('supply_listing__isnull', False), ('supply_opportunity__isnull', False), _connector='OR')), models.Q(('lane', 'POTENTIAL_SUPPLIER'), ('supplier_organization__isnull', False)), models.Q(('lane', 'BROKER_PATH'), ('broker_organization__isnull', False)), _connector='OR'), name='check_candidate_lane_source_consistency'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fit_score__gte', 0), ('fit_score__lte', 100)), ('fit_score__isnull', True), _connector='OR'), name='check_candidate_fit_score_range'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence_coverage__gte', 0), ('evidence_coverage__lte', 100)), ('evidence_coverage__isnull', True), _connector='OR'), name='check_candidate_evidence_coverage_range'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ranking_score__gte', 0), ('ranking_score__lte', 100)), ('ranking_score__isnull', True), _connector='OR'), name='check_candidate_ranking_score_range'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0), ('rank__isnull', True), _connector='OR'), name='check_candidate_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('supply_listing__isnull', False)), fields=('run', 'supply_listing'), name='unique_candidate_run_supply_listing'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('supply_opportunity__isnull', False)), fields=('run', 'supply_opportunity'), name='unique_candidate_run_supply_opportunity'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_organization__isnull', False)), fields=('run', 'supplier_organization'), name='unique_candidate_run_supplier_organization'),
        ),
        migrations.AddConstraint(
            model_name='matchingcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_organization__isnull', False)), fields=('run', 'broker_organization'), name='unique_candidate_run_broker_organization'),
        ),
        migrations.AddIndex(
            model_name='matchingsignal',
            index=models.Index(fields=['candidate', 'dimension'], name='idx_match_sig_cand_dim'),
        ),
        migrations.AddIndex(
            model_name='matchingsignal',
            index=models.Index(fields=['outcome'], name='idx_match_sig_outcome'),
        ),
        migrations.AddIndex(
            model_name='matchingsignal',
            index=models.Index(fields=['code'], name='idx_match_sig_code'),
        ),
        migrations.AddConstraint(
            model_name='matchingsignal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('raw_score__gte', 0), ('raw_score__lte', 1)), ('raw_score__isnull', True), _connector='OR'), name='check_signal_raw_score_range'),
        ),
        migrations.AddConstraint(
            model_name='matchingsignal',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__isnull', True), _connector='OR'), name='check_signal_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='matchingsignal',
            constraint=models.CheckConstraint(condition=models.Q(('contribution__gte', 0), ('contribution__isnull', True), _connector='OR'), name='check_signal_contribution_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='matchingsignal',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['PASS', 'PARTIAL', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE'])), name='check_valid_signal_outcome'),
        ),
        migrations.AddConstraint(
            model_name='matchingsignal',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ['SPECIFICATION', 'QUANTITY', 'AVAILABILITY', 'GEOGRAPHY', 'TRUST', 'HISTORY'])), name='check_valid_signal_dimension'),
        ),
    ]
