# Generated by Django 6.0.8 on 2026-09-17 16:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_commodityattributesemanticidentity_and_more'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationMatchingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('EXACT', 'Exact'), ('MIN_REQUIRED', 'Min Required'), ('MAX_ALLOWED', 'Max Allowed'), ('TARGET_WITH_TOLERANCE', 'Target With Tolerance'), ('IGNORE', 'Ignore')], default='EXACT', help_text='Operator for comparing RFQ target against candidate actual value.', max_length=30)),
                ('hard_constraint', models.BooleanField(default=False, help_text='If True, candidate mismatch results in hard failure (candidate ineligible).')),
                ('relative_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Relative contribution weight within the specification dimension (>= 0).', max_digits=6)),
                ('tolerance', models.DecimalField(blank=True, decimal_places=4, help_text='Allowed numeric tolerance for TARGET_WITH_TOLERANCE operator (must be >= 0).', max_digits=12, null=True)),
                ('missing_data_policy', models.CharField(choices=[('PASS', 'Pass'), ('PARTIAL', 'Partial'), ('FAIL', 'Fail'), ('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not Applicable')], default='UNKNOWN', help_text='Outcome when candidate lacks evidence for this attribute (default UNKNOWN).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_version', models.ForeignKey(help_text='Matching policy version that owns this specification rule.', on_delete=django.db.models.deletion.CASCADE, related_name='specification_rules', to='matching.matchingpolicyversion')),
                ('semantic_identity', models.ForeignKey(help_text='The semantic identity of the attribute evaluated by this rule.', on_delete=django.db.models.deletion.PROTECT, related_name='specification_matching_rules', to='commodities.commodityattributesemanticidentity')),
            ],
            options={
                'ordering': ['policy_version', 'semantic_identity'],
                'indexes': [models.Index(fields=['policy_version', 'semantic_identity'], name='idx_spec_rule_pol_sem')],
                'constraints': [models.UniqueConstraint(fields=('policy_version', 'semantic_identity'), name='unique_spec_rule_policy_semantic_identity'), models.CheckConstraint(condition=models.Q(('relative_weight__gte', 0)), name='check_spec_rule_weight_nonneg'), models.CheckConstraint(condition=models.Q(('operator__in', ['EXACT', 'MIN_REQUIRED', 'MAX_ALLOWED', 'TARGET_WITH_TOLERANCE', 'IGNORE'])), name='check_spec_rule_valid_operator'), models.CheckConstraint(condition=models.Q(('missing_data_policy__in', ['PASS', 'PARTIAL', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE'])), name='check_spec_rule_valid_missing_policy'), models.CheckConstraint(condition=models.Q(('tolerance__isnull', True), ('tolerance__gte', 0), _connector='OR'), name='check_spec_rule_tolerance_nonneg')],
            },
        ),
    ]
