# Generated by Django 6.0.8 on 2026-09-17 19:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_specificationmatchingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationMatchingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified'), ('documents_submitted', 'Documents Submitted'), ('under_review', 'Under Review'), ('basic_verified', 'Basic Verified'), ('verified', 'Verified'), ('suspended', 'Suspended')], help_text='Organization verification status to evaluate.', max_length=50)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized score in [0.0000, 1.0000]. Must be null if hard_exclude is True.', max_digits=5, null=True)),
                ('hard_exclude', models.BooleanField(default=False, help_text='If True, candidate with this verification status is hard excluded (candidate ineligible).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_version', models.ForeignKey(help_text='Matching policy version that owns this verification rule.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_rules', to='matching.matchingpolicyversion')),
            ],
            options={
                'ordering': ['policy_version', 'verification_state'],
                'indexes': [models.Index(fields=['policy_version', 'verification_state'], name='idx_ver_rule_pol_state')],
                'constraints': [models.UniqueConstraint(fields=('policy_version', 'verification_state'), name='unique_verification_rule_policy_state'), models.CheckConstraint(condition=models.Q(('verification_state__in', ['unverified', 'documents_submitted', 'under_review', 'basic_verified', 'verified', 'suspended'])), name='check_valid_verification_rule_state'), models.CheckConstraint(condition=models.Q(('raw_score__isnull', True), models.Q(('raw_score__gte', Decimal('0.0000')), ('raw_score__lte', Decimal('1.0000'))), _connector='OR'), name='check_verification_rule_score_range')],
            },
        ),
    ]
