# Generated by Django 6.0.8 on 2026-09-18 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0010_opportunity_origin_area'),
        ('organizations', '0005_organizationoperatingarea'),
        ('trade_hub', '0004_rfq_destination_area_rfq_origin_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offeror_role', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('BROKER', 'Broker')], help_text='Role assumed by the offeror (SUPPLIER or BROKER).', max_length=20)),
                ('aggregate_version', models.IntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Platform user who recorded or entered the offer.', on_delete=django.db.models.deletion.PROTECT, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
                ('external_counterparty', models.ForeignKey(blank=True, help_text='Off-platform external counterparty for operator-entered offers (mutually exclusive with offering_organization).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='opportunities.externalcounterparty')),
                ('offering_organization', models.ForeignKey(blank=True, help_text='Internal platform organization making the offer (mutually exclusive with external_counterparty).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='organizations.organization')),
                ('rfq', models.ForeignKey(help_text='Target RFQ for this offer thread.', on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='trade_hub.rfq')),
                ('source_opportunity', models.ForeignKey(blank=True, help_text='Originating lead/opportunity provenance context.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rfq', '-created_at'], name='idx_offer_rfq_created_at'), models.Index(fields=['offering_organization'], name='idx_offer_offering_org'), models.Index(fields=['external_counterparty'], name='idx_offer_ext_counterparty'), models.Index(fields=['source_opportunity'], name='idx_offer_source_opp')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('offering_organization__isnull', False), ('external_counterparty__isnull', True)), models.Q(('offering_organization__isnull', True), ('external_counterparty__isnull', False)), _connector='OR'), name='check_offer_economic_party_exclusive'), models.CheckConstraint(condition=models.Q(('offeror_role__in', ['SUPPLIER', 'BROKER'])), name='check_offer_valid_offeror_role'), models.UniqueConstraint(condition=models.Q(('offering_organization__isnull', False)), fields=('rfq', 'offering_organization', 'offeror_role'), name='unique_offer_rfq_organization_role'), models.UniqueConstraint(condition=models.Q(('external_counterparty__isnull', False)), fields=('rfq', 'external_counterparty', 'offeror_role'), name='unique_offer_rfq_external_counterparty_role')],
            },
        ),
    ]
