# Generated by Django 6.0.8 on 2026-09-18 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_commodityattributesemanticidentity_and_more'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Authoritative server-allocated sequential version number (1, 2, ...).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', help_text='Lifecycle status: DRAFT or SUBMITTED.', max_length=20)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Dynamic specification attributes validated against schema_version.')),
                ('offered_quantity', models.DecimalField(decimal_places=3, help_text='Proposed quantity (strictly positive; partial or surplus allowed).', max_digits=15)),
                ('quantity_unit', models.CharField(help_text='Unit of measurement (must be compatible with RFQ unit).', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Proposed price per unit (strictly positive).', max_digits=14)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 3-letter currency code (exact submitted truth; no FX).', max_length=3)),
                ('payment_terms', models.CharField(blank=True, help_text='Proposed payment terms (e.g. LC at sight, TT 30 days).', max_length=255)),
                ('delivery_terms', models.CharField(blank=True, help_text='Proposed delivery conditions or freight details.', max_length=255)),
                ('incoterm', models.CharField(blank=True, help_text='Incoterm code (e.g. FOB, CIF, CFR, EXW).', max_length=10)),
                ('delivery_start', models.DateField(blank=True, help_text='Earliest proposed delivery date.', null=True)),
                ('delivery_end', models.DateField(blank=True, help_text='Latest proposed delivery date.', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Proposal validity timestamp (expiry derived, not mutated).', null=True)),
                ('logistics_cost_status', models.CharField(choices=[('KNOWN_SEPARATE', 'Known Separate'), ('INCLUDED_IN_PRICE', 'Included in Price'), ('NOT_APPLICABLE', 'Not Applicable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Status of logistics cost knowledge.', max_length=20)),
                ('logistics_cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Separate logistics cost amount (required if KNOWN_SEPARATE; absent otherwise).', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, help_text='Commercial notes or comments accompanying the version.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when version was submitted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Platform user who created this version draft.', on_delete=django.db.models.deletion.PROTECT, related_name='created_offer_versions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(help_text='Parent offer aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='offers.offer')),
                ('schema_version', models.ForeignKey(help_text='Exact schema version bound to the parent RFQ.', on_delete=django.db.models.deletion.PROTECT, related_name='offer_versions', to='commodities.commodityschemaversion')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Platform user who submitted this version.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_offer_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Version',
                'verbose_name_plural': 'Offer Versions',
                'ordering': ['offer', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='OfferCostComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], help_text='Cost component kind (LOGISTICS or OTHER).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount (strictly positive).', max_digits=14)),
                ('currency', models.CharField(help_text='ISO 4217 3-letter currency code (must equal OfferVersion currency).', max_length=3)),
                ('description', models.CharField(blank=True, help_text='Description or itemization notes for this cost component.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_version', models.ForeignKey(help_text='Parent OfferVersion commercial snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='cost_components', to='offers.offerversion')),
            ],
            options={
                'verbose_name': 'Offer Cost Component',
                'verbose_name_plural': 'Offer Cost Components',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='current_submitted_version',
            field=models.ForeignKey(blank=True, help_text='Currently active submitted OfferVersion commercial snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.offerversion'),
        ),
        migrations.AddIndex(
            model_name='offerversion',
            index=models.Index(fields=['offer', 'status'], name='idx_offer_version_status'),
        ),
        migrations.AddIndex(
            model_name='offerversion',
            index=models.Index(fields=['offer', 'version_number'], name='idx_offer_version_num'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('offer',), name='unique_one_draft_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.UniqueConstraint(fields=('offer', 'version_number'), name='unique_offer_version_number'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(('offered_quantity__gt', 0)), name='check_offer_version_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='check_offer_version_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED'])), name='check_offer_version_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(('logistics_cost_status__in', ['KNOWN_SEPARATE', 'INCLUDED_IN_PRICE', 'NOT_APPLICABLE', 'UNKNOWN'])), name='check_offer_version_valid_logistics_status'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('logistics_cost_status', 'KNOWN_SEPARATE'), ('logistics_cost_amount__isnull', False), ('logistics_cost_amount__gte', 0)), models.Q(models.Q(('logistics_cost_status', 'KNOWN_SEPARATE'), _negated=True), ('logistics_cost_amount__isnull', True)), _connector='OR'), name='check_offer_version_logistics_cost_consistency'),
        ),
        migrations.AddConstraint(
            model_name='offerversion',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_start__isnull', True), ('delivery_end__isnull', True), ('delivery_start__lte', models.F('delivery_end')), _connector='OR'), name='check_offer_version_delivery_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='offercostcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='check_cost_component_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='offercostcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['LOGISTICS', 'OTHER'])), name='check_cost_component_valid_kind'),
        ),
    ]
