# Generated by Django 6.0.8 on 2026-09-18 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerversion_offercostcomponent_and_more'),
        ('trade_hub', '0004_rfq_destination_area_rfq_origin_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Canonical unique code identifying this profile (e.g. 'default-procurement-decision').", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable decision profile name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of decision policy objectives and scope.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='idx_dec_profile_code')],
            },
        ),
        migrations.CreateModel(
            name='DecisionProfileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing version number (must be > 0).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', help_text='Current lifecycle state of this profile version.', max_length=20)),
                ('minimum_coverage', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Minimum required evidence coverage percentage [0.00, 100.00] (Contract §50).', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Release notes or rationale for this policy version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(help_text='Owning decision profile.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='offers.decisionprofile')),
            ],
            options={
                'ordering': ['profile', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DecisionDimensionWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('COST', 'Cost'), ('QUALITY', 'Quality'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('TRUST', 'Trust'), ('COMPLETENESS', 'Completeness')], help_text='Procurement evaluation dimension.', max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Configured dimension weight percentage [0.00, 100.00].', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_version', models.ForeignKey(help_text='Owning profile version.', on_delete=django.db.models.deletion.CASCADE, related_name='dimension_weights', to='offers.decisionprofileversion')),
            ],
            options={
                'ordering': ['profile_version', 'dimension'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_version', models.CharField(default='decision-engine-v1', help_text='Centralized semantic decision engine contract version.', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the decision run was initiated.')),
                ('input_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 fingerprint of the canonical decision inputs.', max_length=64)),
                ('result_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 fingerprint of the decision results (reserved for T0809).', max_length=64)),
                ('target_snapshot', models.JSONField(blank=True, default=dict, help_text='Canonical frozen snapshot of RFQ procurement demand at run creation.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Authenticated Buyer or Operator actor who initiated the decision run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_decision_runs', to=settings.AUTH_USER_MODEL)),
                ('decision_profile_version', models.ForeignKey(help_text='Published decision profile version used for evaluation.', on_delete=django.db.models.deletion.PROTECT, related_name='decision_runs', to='offers.decisionprofileversion')),
                ('rfq', models.ForeignKey(help_text='Target RFQ procurement demand.', on_delete=django.db.models.deletion.PROTECT, related_name='decision_runs', to='trade_hub.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_score', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted decision score percentage [0.00, 100.00] (Contract §47).', max_digits=6, null=True)),
                ('evidence_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Evidence coverage percentage [0.00, 100.00] (Contract §48).', max_digits=6, null=True)),
                ('effective_score', models.DecimalField(blank=True, decimal_places=2, help_text='Effective decision score percentage [0.00, 100.00] (Contract §49).', max_digits=6, null=True)),
                ('award_eligible', models.BooleanField(blank=True, default=None, help_text='Award eligibility gate outcome. None indicates unevaluated prior to T0809 hard conditions.', null=True)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Deterministic rank position (positive integer >= 1) among evaluated candidates.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(help_text='Parent offer negotiation thread.', on_delete=django.db.models.deletion.PROTECT, related_name='decision_candidates', to='offers.offer')),
                ('offer_version', models.ForeignKey(help_text='Exact immutable commercial snapshot evaluated.', on_delete=django.db.models.deletion.PROTECT, related_name='decision_candidates', to='offers.offerversion')),
                ('decision_run', models.ForeignKey(help_text='Associated decision run execution.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='offers.decisionrun')),
            ],
            options={
                'ordering': ['decision_run', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('COST', 'Cost'), ('QUALITY', 'Quality'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('TRUST', 'Trust'), ('COMPLETENESS', 'Completeness')], help_text='Evaluation dimension (COST, QUALITY, DELIVERY, PAYMENT, TRUST, COMPLETENESS).', max_length=30)),
                ('code', models.CharField(help_text="Machine-readable rule or signal code (e.g. 'cost.landed_unit_cost').", max_length=100)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('PARTIAL', 'Partial'), ('FAIL', 'Fail'), ('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Structured outcome: PASS, PARTIAL, FAIL, UNKNOWN, NOT_APPLICABLE.', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Dimension or signal weight percentage (>= 0).', max_digits=6, null=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized score in [0.0000, 1.0000] for known evaluation. Null for UNKNOWN/NOT_APPLICABLE.', max_digits=5, null=True)),
                ('contribution', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted contribution towards candidate score (>= 0).', max_digits=6, null=True)),
                ('expected_value', models.JSONField(blank=True, default=dict, help_text='Structured JSONB representing target RFQ expectation.', null=True)),
                ('actual_value', models.JSONField(blank=True, default=dict, help_text='Structured JSONB representing candidate actual commercial proposal.', null=True)),
                ('reason_code', models.CharField(blank=True, default='', help_text='Machine-readable reason code (never localized text).', max_length=100)),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Sanitized decision-relevant facts. Strictly excludes private CRM/contact data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(help_text='Candidate evaluated by this signal.', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='offers.decisioncandidate')),
            ],
            options={
                'ordering': ['candidate', 'dimension', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionprofileversion',
            index=models.Index(fields=['profile', 'version'], name='idx_dec_prof_ver'),
        ),
        migrations.AddIndex(
            model_name='decisionprofileversion',
            index=models.Index(fields=['status'], name='idx_dec_prof_status'),
        ),
        migrations.AddConstraint(
            model_name='decisionprofileversion',
            constraint=models.UniqueConstraint(fields=('profile', 'version'), name='unique_dec_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='decisionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='check_pos_dec_profile_ver'),
        ),
        migrations.AddConstraint(
            model_name='decisionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'RETIRED'])), name='check_valid_dec_profile_status'),
        ),
        migrations.AddConstraint(
            model_name='decisionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_coverage__gte', 0), ('minimum_coverage__lte', 100)), name='check_valid_dec_min_coverage'),
        ),
        migrations.AddIndex(
            model_name='decisiondimensionweight',
            index=models.Index(fields=['profile_version', 'dimension'], name='idx_dec_pv_dim'),
        ),
        migrations.AddConstraint(
            model_name='decisiondimensionweight',
            constraint=models.UniqueConstraint(fields=('profile_version', 'dimension'), name='unique_dec_pv_dim'),
        ),
        migrations.AddConstraint(
            model_name='decisiondimensionweight',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='check_valid_dec_dim_weight'),
        ),
        migrations.AddConstraint(
            model_name='decisiondimensionweight',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ['COST', 'QUALITY', 'DELIVERY', 'PAYMENT', 'TRUST', 'COMPLETENESS'])), name='check_valid_dec_dim_choice'),
        ),
        migrations.AddIndex(
            model_name='decisionrun',
            index=models.Index(fields=['rfq', '-created_at'], name='idx_dec_run_rfq_created'),
        ),
        migrations.AddIndex(
            model_name='decisionrun',
            index=models.Index(fields=['input_fingerprint'], name='idx_dec_run_input_fp'),
        ),
        migrations.AddIndex(
            model_name='decisioncandidate',
            index=models.Index(fields=['decision_run', 'offer'], name='idx_dec_cand_run_offer'),
        ),
        migrations.AddIndex(
            model_name='decisioncandidate',
            index=models.Index(fields=['decision_run', 'rank'], name='idx_dec_cand_run_rank'),
        ),
        migrations.AddConstraint(
            model_name='decisioncandidate',
            constraint=models.UniqueConstraint(fields=('decision_run', 'offer_version'), name='unique_dec_run_off_ver'),
        ),
        migrations.AddConstraint(
            model_name='decisioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('rank__isnull', True), ('rank__gte', 1), _connector='OR'), name='check_pos_dec_cand_rank'),
        ),
        migrations.AddConstraint(
            model_name='decisioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('decision_score__isnull', True), models.Q(('decision_score__gte', 0), ('decision_score__lte', 100)), _connector='OR'), name='check_dec_cand_score_range'),
        ),
        migrations.AddConstraint(
            model_name='decisioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_coverage__isnull', True), models.Q(('evidence_coverage__gte', 0), ('evidence_coverage__lte', 100)), _connector='OR'), name='check_dec_cand_cov_range'),
        ),
        migrations.AddConstraint(
            model_name='decisioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('effective_score__isnull', True), models.Q(('effective_score__gte', 0), ('effective_score__lte', 100)), _connector='OR'), name='check_dec_cand_eff_range'),
        ),
        migrations.AddIndex(
            model_name='decisionsignal',
            index=models.Index(fields=['candidate', 'dimension', 'code'], name='idx_dec_sig_cand_dim_code'),
        ),
        migrations.AddConstraint(
            model_name='decisionsignal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PASS', 'PARTIAL', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE'])), name='check_valid_dec_sig_status'),
        ),
        migrations.AddConstraint(
            model_name='decisionsignal',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ['COST', 'QUALITY', 'DELIVERY', 'PAYMENT', 'TRUST', 'COMPLETENESS'])), name='check_valid_dec_sig_dim'),
        ),
        migrations.AddConstraint(
            model_name='decisionsignal',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gte', 0), _connector='OR'), name='check_dec_sig_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='decisionsignal',
            constraint=models.CheckConstraint(condition=models.Q(('raw_score__isnull', True), models.Q(('raw_score__gte', 0), ('raw_score__lte', 1)), _connector='OR'), name='check_dec_sig_raw_score_range'),
        ),
        migrations.AddConstraint(
            model_name='decisionsignal',
            constraint=models.CheckConstraint(condition=models.Q(('contribution__isnull', True), ('contribution__gte', 0), _connector='OR'), name='check_dec_sig_contrib_nonneg'),
        ),
    ]
