# Generated by Django 6.0.8 on 2026-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_decisionprofile_decisionprofileversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisioncandidate',
            name='eligibility_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Structured machine-readable exclusion reason codes if not award-eligible.'),
        ),
        migrations.AddField(
            model_name='decisioncandidate',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Whether this candidate is the single recommended offer for award under the evaluated policy.'),
        ),
    ]
