# Generated by Django 6.0.8 on 2026-09-18 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_decisioncandidate_eligibility_reasons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_fields', models.JSONField(default=list, help_text='Canonical list of field names requested for revision.')),
                ('message', models.TextField(blank=True, default='', help_text='Human-entered revision explanation or instruction.')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when revision request was created.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Revision request lifecycle status: OPEN, RESOLVED, DECLINED, CANCELLED.', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when request was resolved, declined, or cancelled.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_offer_version', models.ForeignKey(help_text='Target submitted OfferVersion being revised.', on_delete=django.db.models.deletion.PROTECT, related_name='base_revision_requests', to='offers.offerversion')),
                ('offer', models.ForeignKey(help_text='Parent offer aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='revision_requests', to='offers.offer')),
                ('requested_by', models.ForeignKey(help_text='Platform user who initiated the revision request.', on_delete=django.db.models.deletion.PROTECT, related_name='requested_revisions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by_version', models.ForeignKey(blank=True, help_text='Revised OfferVersion that resolves this request (T0811).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolving_revision_requests', to='offers.offerversion')),
            ],
            options={
                'verbose_name': 'Revision Request',
                'verbose_name_plural': 'Revision Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['offer', 'status'], name='idx_rev_req_offer_status'), models.Index(fields=['base_offer_version'], name='idx_rev_req_base_ver'), models.Index(fields=['-requested_at'], name='idx_rev_req_requested_at')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('offer',), name='unique_open_revision_request_per_offer'), models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RESOLVED', 'DECLINED', 'CANCELLED'])), name='check_revision_request_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), ('resolved_by_version__isnull', False)), models.Q(models.Q(('status', 'RESOLVED'), _negated=True), ('resolved_by_version__isnull', True)), _connector='OR'), name='check_revision_request_resolution_consistency')],
            },
        ),
    ]
