# Generated by Django 6.0.8 on 2026-09-19 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_revisionrequest'),
        ('trade_hub', '0004_rfq_destination_area_rfq_origin_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', help_text='Lifecycle status of the award (DRAFT or FINALIZED).', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when the award was finalized.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Platform user who created the draft award.', on_delete=django.db.models.deletion.PROTECT, related_name='created_awards', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, help_text='Platform user who authoritatively finalized the award.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_awards', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.OneToOneField(help_text='Target RFQ for this procurement award aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='award', to='trade_hub.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_quantity', models.DecimalField(decimal_places=3, help_text='Awarded commercial quantity (strictly positive Decimal).', max_digits=15)),
                ('quantity_unit', models.CharField(help_text='Commercial unit of measurement (must match RFQ and OfferVersion).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(help_text='Parent award aggregate.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='offers.award')),
                ('offer', models.ForeignKey(help_text='Parent offer thread.', on_delete=django.db.models.deletion.PROTECT, related_name='award_allocations', to='offers.offer')),
                ('offer_version', models.ForeignKey(help_text='Exact selected OfferVersion commercial snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='award_allocations', to='offers.offerversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['rfq', 'status'], name='idx_award_rfq_status'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'FINALIZED'])), name='check_valid_award_status'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_award_version'),
        ),
        migrations.AddIndex(
            model_name='awardallocation',
            index=models.Index(fields=['award', 'offer'], name='idx_alloc_award_offer'),
        ),
        migrations.AddConstraint(
            model_name='awardallocation',
            constraint=models.UniqueConstraint(fields=('award', 'offer_version'), name='unique_award_offer_version'),
        ),
        migrations.AddConstraint(
            model_name='awardallocation',
            constraint=models.CheckConstraint(condition=models.Q(('awarded_quantity__gt', 0)), name='check_positive_awarded_quantity'),
        ),
    ]
