# Generated by Django 6.0.8 on 2026-09-11 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_organizationmembership_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("documents_submitted", "Documents Submitted"),
                            ("under_review", "Under Review"),
                            ("basic_verified", "Basic Verified"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        default="unverified",
                        max_length=50,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("documents_submitted", "Documents Submitted"),
                            ("under_review", "Under Review"),
                            ("basic_verified", "Basic Verified"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("documents_submitted", "Documents Submitted"),
                            ("under_review", "Under Review"),
                            ("basic_verified", "Basic Verified"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="organizations_verification.organizationverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="organizations_verification.organizationverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="organizationverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "unverified",
                            "documents_submitted",
                            "under_review",
                            "basic_verified",
                            "verified",
                            "suspended",
                        ],
                    )
                ),
                name="check_valid_verification_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "previous_status__in",
                        [
                            "unverified",
                            "documents_submitted",
                            "under_review",
                            "basic_verified",
                            "verified",
                            "suspended",
                        ],
                    )
                ),
                name="check_valid_previous_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "new_status__in",
                        [
                            "unverified",
                            "documents_submitted",
                            "under_review",
                            "basic_verified",
                            "verified",
                            "suspended",
                        ],
                    )
                ),
                name="check_valid_new_status",
            ),
        ),
    ]
