# Generated by Django 6.0.8 on 2026-09-12 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations_verification", "0002_verificationdecision_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdecision",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submit", "Submit"),
                    ("start_review", "Start Review"),
                    ("approve_basic", "Approve Basic"),
                    ("approve_full", "Approve Full"),
                    ("reject", "Reject"),
                    ("suspend", "Suspend"),
                    ("reopen", "Reopen"),
                    (
                        "evidence_replacement_invalidation",
                        "Evidence Replacement Invalidation",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action__isnull", True),
                    (
                        "action__in",
                        [
                            "submit",
                            "start_review",
                            "approve_basic",
                            "approve_full",
                            "reject",
                            "suspend",
                            "reopen",
                            "evidence_replacement_invalidation",
                        ],
                    ),
                    _connector="OR",
                ),
                name="check_valid_decision_action",
            ),
        ),
    ]
