# Generated by Django 6.0.8 on 2026-09-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations_verification",
            "0003_alter_verificationdecision_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationchecklistreview",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="verificationdecision",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="verificationnote",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
