from django.urls import path

from execution.api.views import (
    ExecutionDetailView,
    ExecutionInspectionCancelActionView,
    ExecutionInspectionCompleteActionView,
    ExecutionInspectionDetailView,
    ExecutionInspectionMarkNotRequiredActionView,
    ExecutionInspectionScheduleActionView,
    ExecutionLogisticsDetailView,
    ExecutionLogisticsRecordDeliveryActionView,
    ExecutionLogisticsRecordLoadingActionView,
    ExecutionLogisticsScheduleLoadingActionView,
    ExecutionLogisticsUpdateCostActionView,
    ExecutionLogisticsUpdateETAActionView,
    ExecutionLogisticsUpdateTransportActionView,
    ExecutionTimelineView,
    ExecutionWorkflowTemplateActiveVersionView,
    ExecutionWorkflowTemplateDetailView,
    ExecutionWorkflowTemplateListView,
    ExecutionWorkflowTemplateVersionDetailView,
    MilestoneBlockActionView,
    MilestoneCompleteActionView,
    MilestoneSkipActionView,
    MilestoneStartActionView,
)

urlpatterns = [
    path("templates/", ExecutionWorkflowTemplateListView.as_view(), name="execution-workflow-template-list"),
    path("templates/<str:code_or_id>/", ExecutionWorkflowTemplateDetailView.as_view(), name="execution-workflow-template-detail"),
    path("templates/<str:code>/active-version/", ExecutionWorkflowTemplateActiveVersionView.as_view(), name="execution-workflow-template-active-version"),
    path("versions/<uuid:version_id>/", ExecutionWorkflowTemplateVersionDetailView.as_view(), name="execution-workflow-version-detail"),
    path("<uuid:execution_id>/", ExecutionDetailView.as_view(), name="execution-detail"),
    path("<uuid:execution_id>/logistics/", ExecutionLogisticsDetailView.as_view(), name="execution-logistics-detail"),
    path("<uuid:execution_id>/logistics/schedule-loading/", ExecutionLogisticsScheduleLoadingActionView.as_view(), name="execution-logistics-schedule-loading"),
    path("<uuid:execution_id>/logistics/record-loading/", ExecutionLogisticsRecordLoadingActionView.as_view(), name="execution-logistics-record-loading"),
    path("<uuid:execution_id>/logistics/update-transport/", ExecutionLogisticsUpdateTransportActionView.as_view(), name="execution-logistics-update-transport"),
    path("<uuid:execution_id>/logistics/update-eta/", ExecutionLogisticsUpdateETAActionView.as_view(), name="execution-logistics-update-eta"),
    path("<uuid:execution_id>/logistics/record-delivery/", ExecutionLogisticsRecordDeliveryActionView.as_view(), name="execution-logistics-record-delivery"),
    path("<uuid:execution_id>/logistics/update-cost/", ExecutionLogisticsUpdateCostActionView.as_view(), name="execution-logistics-update-cost"),
    path("<uuid:execution_id>/inspection/", ExecutionInspectionDetailView.as_view(), name="execution-inspection-detail"),
    path("<uuid:execution_id>/inspection/schedule/", ExecutionInspectionScheduleActionView.as_view(), name="execution-inspection-schedule"),
    path("<uuid:execution_id>/inspection/complete/", ExecutionInspectionCompleteActionView.as_view(), name="execution-inspection-complete"),
    path("<uuid:execution_id>/inspection/cancel/", ExecutionInspectionCancelActionView.as_view(), name="execution-inspection-cancel"),
    path("<uuid:execution_id>/inspection/mark-not-required/", ExecutionInspectionMarkNotRequiredActionView.as_view(), name="execution-inspection-mark-not-required"),
    path("<uuid:execution_id>/timeline/", ExecutionTimelineView.as_view(), name="execution-timeline"),
    path("<uuid:execution_id>/milestones/<uuid:milestone_id>/start/", MilestoneStartActionView.as_view(), name="execution-milestone-start"),
    path("<uuid:execution_id>/milestones/<uuid:milestone_id>/complete/", MilestoneCompleteActionView.as_view(), name="execution-milestone-complete"),
    path("<uuid:execution_id>/milestones/<uuid:milestone_id>/block/", MilestoneBlockActionView.as_view(), name="execution-milestone-block"),
    path("<uuid:execution_id>/milestones/<uuid:milestone_id>/skip/", MilestoneSkipActionView.as_view(), name="execution-milestone-skip"),
]


