# Generated by Django 6.0.8 on 2026-09-11 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_organizationmembership_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("company_registration", "Company Registration"),
                            ("tax_id", "Tax ID"),
                            ("trade_license", "Trade License"),
                            ("bank_details", "Bank Details"),
                            ("authorized_representative", "Authorized Representative"),
                            ("certifications", "Certifications"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("mime_type", models.CharField(max_length=127)),
                ("size_bytes", models.IntegerField()),
                (
                    "verification_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("verification_version", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "company_registration",
                                    "tax_id",
                                    "trade_license",
                                    "bank_details",
                                    "authorized_representative",
                                    "certifications",
                                ],
                            )
                        ),
                        name="check_valid_document_type",
                    )
                ],
            },
        ),
    ]
