# Generated by Django 6.0.8 on 2026-09-12 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("organizations", "0004_organizationcommodity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationdocument",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="verificationdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("organization", "type"),
                name="unique_current_document_per_type",
            ),
        ),
    ]
