# Generated by Django 6.0.8 on 2026-09-23 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0006_award_awardallocation_award_idx_award_rfq_status_and_more'),
        ('opportunities', '0010_opportunity_origin_area'),
        ('organizations', '0005_organizationoperatingarea'),
        ('trade_hub', '0004_rfq_destination_area_rfq_origin_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(help_text='Source Award aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='offers.award')),
                ('award_allocation', models.OneToOneField(help_text='Authoritative source AwardAllocation (1 allocation -> exactly 1 Deal).', on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='offers.awardallocation')),
                ('buyer_organization', models.ForeignKey(help_text='Buyer Organization (authoritatively derived from RFQ.organization).', on_delete=django.db.models.deletion.PROTECT, related_name='buyer_deals', to='organizations.organization')),
                ('created_by', models.ForeignKey(help_text='Platform user who authoritatively materialized this deal.', on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(help_text='Source Offer negotiation thread.', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='offers.offer')),
                ('offer_version', models.ForeignKey(help_text='Exact selected OfferVersion commercial snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='offers.offerversion')),
                ('rfq', models.ForeignKey(help_text='Target RFQ for this commercial deal.', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='trade_hub.rfq')),
                ('seller_external_counterparty', models.ForeignKey(blank=True, help_text='Off-platform external counterparty seller (mutually exclusive with seller_organization).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='opportunities.externalcounterparty')),
                ('seller_organization', models.ForeignKey(blank=True, help_text='Internal seller organization (mutually exclusive with seller_external_counterparty).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_deals', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['award'], name='idx_deal_award'), models.Index(fields=['rfq'], name='idx_deal_rfq'), models.Index(fields=['buyer_organization'], name='idx_deal_buyer_org'), models.Index(fields=['seller_organization'], name='idx_deal_seller_org'), models.Index(fields=['seller_external_counterparty'], name='idx_deal_seller_ext'), models.Index(fields=['-created_at'], name='idx_deal_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('seller_organization__isnull', False), ('seller_external_counterparty__isnull', True)), models.Q(('seller_organization__isnull', True), ('seller_external_counterparty__isnull', False)), _connector='OR'), name='check_deal_seller_exclusive')],
            },
        ),
    ]
