# Generated by Django 6.0.8 on 2026-09-23 10:51

from decimal import Decimal, ROUND_HALF_UP
import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_existing_deals(apps, schema_editor):
    """
    Safely backfill DealTermsSnapshot, DealCostSnapshot, and DealPartySnapshot
    for any pre-existing T0901 Deals in an upgrade scenario.
    Uses exact authoritative source data without inventing any values.
    """
    Deal = apps.get_model('deals', 'Deal')
    DealTermsSnapshot = apps.get_model('deals', 'DealTermsSnapshot')
    DealCostSnapshot = apps.get_model('deals', 'DealCostSnapshot')
    DealPartySnapshot = apps.get_model('deals', 'DealPartySnapshot')
    OfferCostComponent = apps.get_model('offers', 'OfferCostComponent')

    for deal in Deal.objects.all():
        if not DealTermsSnapshot.objects.filter(deal=deal).exists():
            alloc = deal.award_allocation
            offer_ver = deal.offer_version
            rfq = deal.rfq

            product_cost = (offer_ver.unit_price * alloc.awarded_quantity).quantize(
                Decimal("0.01"), rounding=ROUND_HALF_UP
            )

            terms = DealTermsSnapshot.objects.create(
                deal=deal,
                commodity=rfq.commodity,
                schema_version=offer_ver.schema_version,
                specifications=offer_ver.specifications or {},
                quantity=alloc.awarded_quantity,
                quantity_unit=alloc.quantity_unit,
                unit_price=offer_ver.unit_price,
                currency=offer_ver.currency,
                product_cost_snapshot=product_cost,
                payment_terms=offer_ver.payment_terms or "",
                delivery_terms=offer_ver.delivery_terms or "",
                incoterm=offer_ver.incoterm or "",
                delivery_start=offer_ver.delivery_start,
                delivery_end=offer_ver.delivery_end,
                origin=rfq.origin or "",
                destination=rfq.destination or "",
                origin_area=rfq.origin_area,
                destination_area=rfq.destination_area,
                logistics_cost_status=offer_ver.logistics_cost_status,
                logistics_cost_amount=offer_ver.logistics_cost_amount,
            )

            for cost_comp in OfferCostComponent.objects.filter(offer_version=offer_ver):
                DealCostSnapshot.objects.create(
                    deal_terms_snapshot=terms,
                    kind=cost_comp.kind,
                    amount=cost_comp.amount,
                    currency=cost_comp.currency,
                    description_snapshot=cost_comp.description or "",
                )

        if not DealPartySnapshot.objects.filter(deal=deal, role="BUYER").exists():
            buyer_org = deal.buyer_organization
            DealPartySnapshot.objects.create(
                deal=deal,
                role="BUYER",
                party_type="ORGANIZATION",
                organization=buyer_org,
                name_snapshot=buyer_org.name,
                country_snapshot=getattr(buyer_org, "country", "") or "",
                registration_identifier_snapshot=getattr(buyer_org, "registration_identifier", "") or "",
            )

        if not DealPartySnapshot.objects.filter(deal=deal, role="SELLER").exists():
            if deal.seller_organization_id:
                seller_org = deal.seller_organization
                DealPartySnapshot.objects.create(
                    deal=deal,
                    role="SELLER",
                    party_type="ORGANIZATION",
                    organization=seller_org,
                    name_snapshot=seller_org.name,
                    country_snapshot=getattr(seller_org, "country", "") or "",
                    registration_identifier_snapshot=getattr(seller_org, "registration_identifier", "") or "",
                )
            elif deal.seller_external_counterparty_id:
                seller_ext = deal.seller_external_counterparty
                DealPartySnapshot.objects.create(
                    deal=deal,
                    role="SELLER",
                    party_type="EXTERNAL_COUNTERPARTY",
                    external_counterparty=seller_ext,
                    name_snapshot=seller_ext.company_name,
                    country_snapshot=getattr(seller_ext, "geography", "") or "",
                    registration_identifier_snapshot="",
                )


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_commodityattributesemanticidentity_and_more'),
        ('deals', '0001_initial'),
        ('geography', '0001_initial'),
        ('opportunities', '0010_opportunity_origin_area'),
        ('organizations', '0005_organizationoperatingarea'),
        ('offers', '0006_award_awardallocation_award_idx_award_rfq_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTermsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Canonical deep-copy snapshot of accepted dynamic specifications JSONB.')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Awarded commercial quantity (strictly positive Decimal from AwardAllocation.awarded_quantity).', max_digits=15)),
                ('quantity_unit', models.CharField(help_text='Commercial unit of measurement from AwardAllocation/OfferVersion.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Accepted unit price from exact selected OfferVersion.', max_digits=14)),
                ('currency', models.CharField(help_text='ISO 4217 3-letter currency code from exact selected OfferVersion.', max_length=3)),
                ('product_cost_snapshot', models.DecimalField(decimal_places=2, help_text='Exact Decimal snapshot of unit_price * quantity.', max_digits=20)),
                ('payment_terms', models.CharField(blank=True, help_text='Accepted payment terms from OfferVersion.', max_length=255)),
                ('delivery_terms', models.CharField(blank=True, help_text='Accepted delivery terms from OfferVersion.', max_length=255)),
                ('incoterm', models.CharField(blank=True, help_text='Accepted Incoterm from OfferVersion.', max_length=10)),
                ('delivery_start', models.DateField(blank=True, help_text='Accepted earliest delivery date from OfferVersion.', null=True)),
                ('delivery_end', models.DateField(blank=True, help_text='Accepted latest delivery date from OfferVersion.', null=True)),
                ('origin', models.CharField(blank=True, help_text='Origin location snapshot if present in RFQ context.', max_length=255)),
                ('destination', models.CharField(blank=True, help_text='Destination location snapshot if present in RFQ context.', max_length=255)),
                ('logistics_cost_status', models.CharField(choices=[('KNOWN_SEPARATE', 'Known Separate'), ('INCLUDED_IN_PRICE', 'Included in Price'), ('NOT_APPLICABLE', 'Not Applicable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Logistics cost knowledge status.', max_length=20)),
                ('logistics_cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Separate logistics cost amount if KNOWN_SEPARATE.', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(help_text='Referenced commodity definition.', on_delete=django.db.models.deletion.PROTECT, related_name='deal_terms_snapshots', to='commodities.commoditydefinition')),
                ('deal', models.OneToOneField(help_text='Parent Deal aggregate for this terms snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='terms_snapshot', to='deals.deal')),
                ('destination_area', models.ForeignKey(blank=True, help_text='Destination geographic area reference if present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.geographicarea')),
                ('origin_area', models.ForeignKey(blank=True, help_text='Origin geographic area reference if present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.geographicarea')),
                ('schema_version', models.ForeignKey(help_text='Exact immutable schema version bound at offer/deal creation time.', on_delete=django.db.models.deletion.PROTECT, related_name='deal_terms_snapshots', to='commodities.commodityschemaversion')),
            ],
            options={
                'verbose_name': 'Deal Terms Snapshot',
                'verbose_name_plural': 'Deal Terms Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], help_text='Cost component kind (LOGISTICS or OTHER).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount (strictly positive Decimal).', max_digits=14)),
                ('currency', models.CharField(help_text='ISO 4217 3-letter currency code (must match Deal terms currency).', max_length=3)),
                ('description_snapshot', models.CharField(blank=True, help_text='Description or itemization note snapshot.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_terms_snapshot', models.ForeignKey(help_text='Parent DealTermsSnapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='cost_snapshots', to='deals.dealtermssnapshot')),
            ],
            options={
                'verbose_name': 'Deal Cost Snapshot',
                'verbose_name_plural': 'Deal Cost Snapshots',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealPartySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], help_text='Commercial principal role (BUYER or SELLER).', max_length=20)),
                ('party_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('EXTERNAL_COUNTERPARTY', 'External Counterparty')], help_text='Backing entity type (ORGANIZATION or EXTERNAL_COUNTERPARTY).', max_length=30)),
                ('name_snapshot', models.CharField(help_text='Commercial or legal entity name snapshot.', max_length=255)),
                ('country_snapshot', models.CharField(blank=True, help_text='Country or jurisdiction snapshot.', max_length=255)),
                ('registration_identifier_snapshot', models.CharField(blank=True, help_text='Business registration identifier snapshot.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(help_text='Parent Deal aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='party_snapshots', to='deals.deal')),
                ('external_counterparty', models.ForeignKey(blank=True, help_text='Backing off-platform ExternalCounterparty (required when party_type=EXTERNAL_COUNTERPARTY).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_party_snapshots', to='opportunities.externalcounterparty')),
                ('organization', models.ForeignKey(blank=True, help_text='Backing platform Organization (required when party_type=ORGANIZATION).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_party_snapshots', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Deal Party Snapshot',
                'verbose_name_plural': 'Deal Party Snapshots',
                'ordering': ['role'],
                'indexes': [models.Index(fields=['deal', 'role'], name='idx_deal_party_role'), models.Index(fields=['organization'], name='idx_deal_party_org'), models.Index(fields=['external_counterparty'], name='idx_deal_party_ext'), models.Index(fields=['created_at'], name='idx_deal_party_created_at')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'role'), name='unique_deal_party_role'), models.CheckConstraint(condition=models.Q(('role__in', ['BUYER', 'SELLER'])), name='check_deal_party_role_valid'), models.CheckConstraint(condition=models.Q(('party_type__in', ['ORGANIZATION', 'EXTERNAL_COUNTERPARTY'])), name='check_deal_party_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('party_type', 'ORGANIZATION'), ('organization__isnull', False), ('external_counterparty__isnull', True)), models.Q(('party_type', 'EXTERNAL_COUNTERPARTY'), ('organization__isnull', True), ('external_counterparty__isnull', False)), _connector='OR'), name='check_deal_party_backing_exclusive')],
            },
        ),
        migrations.AddIndex(
            model_name='dealtermssnapshot',
            index=models.Index(fields=['deal'], name='idx_deal_terms_deal'),
        ),
        migrations.AddIndex(
            model_name='dealtermssnapshot',
            index=models.Index(fields=['commodity'], name='idx_deal_terms_commodity'),
        ),
        migrations.AddIndex(
            model_name='dealtermssnapshot',
            index=models.Index(fields=['schema_version'], name='idx_deal_terms_schema'),
        ),
        migrations.AddIndex(
            model_name='dealtermssnapshot',
            index=models.Index(fields=['-created_at'], name='idx_deal_terms_created_at'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_deal_terms_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='check_deal_terms_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('product_cost_snapshot__gt', 0)), name='check_deal_terms_product_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('logistics_cost_status__in', ['KNOWN_SEPARATE', 'INCLUDED_IN_PRICE', 'NOT_APPLICABLE', 'UNKNOWN'])), name='check_deal_terms_valid_logistics_status'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('logistics_cost_status', 'KNOWN_SEPARATE'), ('logistics_cost_amount__isnull', False), ('logistics_cost_amount__gte', 0)), models.Q(models.Q(('logistics_cost_status', 'KNOWN_SEPARATE'), _negated=True), ('logistics_cost_amount__isnull', True)), _connector='OR'), name='check_deal_terms_logistics_cost_consistency'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_start__isnull', True), ('delivery_end__isnull', True), ('delivery_start__lte', models.F('delivery_end')), _connector='OR'), name='check_deal_terms_delivery_window_valid'),
        ),
        migrations.AddIndex(
            model_name='dealcostsnapshot',
            index=models.Index(fields=['deal_terms_snapshot'], name='idx_deal_cost_terms'),
        ),
        migrations.AddIndex(
            model_name='dealcostsnapshot',
            index=models.Index(fields=['created_at'], name='idx_deal_cost_created_at'),
        ),
        migrations.AddConstraint(
            model_name='dealcostsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='check_deal_cost_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='dealcostsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['LOGISTICS', 'OTHER'])), name='check_deal_cost_valid_kind'),
        ),
        migrations.RunPython(backfill_existing_deals, migrations.RunPython.noop),
    ]
