# Generated by Django 6.0.8 on 2026-09-23 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_existing_deals_attribution(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    DealAttribution = apps.get_model("deals", "DealAttribution")
    for deal in Deal.objects.all():
        if not DealAttribution.objects.filter(deal=deal).exists():
            DealAttribution.objects.create(
                deal=deal,
                status="PENDING",
                primary_channel=None,
                resolution_method=None,
                resolved_by=None,
                resolved_at=None,
                resolution_reason="",
                evidence_snapshot={},
                version=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealtermssnapshot_dealcostsnapshot_dealpartysnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', help_text='Attribution resolution status (PENDING or RESOLVED).', max_length=20)),
                ('primary_channel', models.CharField(blank=True, choices=[('PLATFORM_NETWORK', 'Platform Network'), ('DIRECT_SUPPLIER', 'Direct Supplier'), ('BROKER', 'Broker'), ('OPPORTUNITY_DESK', 'Opportunity Desk'), ('BUYER_EXISTING_SUPPLIER', 'Buyer Existing Supplier')], help_text='Authoritative primary attribution business category (null when PENDING).', max_length=40, null=True)),
                ('resolution_method', models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], help_text='Method by which attribution was resolved (AUTOMATIC or MANUAL).', max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Authoritative timestamp when attribution was resolved.', null=True)),
                ('resolution_reason', models.TextField(blank=True, default='', help_text='Explanation or operational reason for the resolution decision.')),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict, help_text='Canonical frozen structured evidence dictionary used by the resolver.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(help_text='Parent Deal aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='attribution', to='deals.deal')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Platform user (Operator/Admin) who authoritatively resolved the attribution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal Attribution',
                'verbose_name_plural': 'Deal Attributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal'], name='idx_deal_attr_deal'), models.Index(fields=['status'], name='idx_deal_attr_status'), models.Index(fields=['primary_channel'], name='idx_deal_attr_channel'), models.Index(fields=['-created_at'], name='idx_deal_attr_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'PENDING'), ('primary_channel__isnull', True)), models.Q(('status', 'RESOLVED'), ('primary_channel__isnull', False)), _connector='OR'), name='check_deal_attribution_status_channel_consistency'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RESOLVED'])), name='check_valid_deal_attribution_status'), models.CheckConstraint(condition=models.Q(('primary_channel__isnull', True), ('primary_channel__in', ['PLATFORM_NETWORK', 'DIRECT_SUPPLIER', 'BROKER', 'OPPORTUNITY_DESK', 'BUYER_EXISTING_SUPPLIER']), _connector='OR'), name='check_valid_deal_attribution_primary_channel'), models.CheckConstraint(condition=models.Q(('resolution_method__isnull', True), ('resolution_method__in', ['AUTOMATIC', 'MANUAL']), _connector='OR'), name='check_valid_deal_attribution_resolution_method'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_deal_attribution_version')],
            },
        ),
        migrations.RunPython(initialize_existing_deals_attribution, migrations.RunPython.noop),
    ]

