# Generated by Django 6.0.8 on 2026-09-23 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_existing_deals_provenance(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    DealBrokerAttribution = apps.get_model("deals", "DealBrokerAttribution")
    DealOpportunityAttribution = apps.get_model("deals", "DealOpportunityAttribution")
    Opportunity = apps.get_model("opportunities", "Opportunity")

    for deal in Deal.objects.all():
        # Demand Opportunity
        demand_opp = Opportunity.objects.filter(converted_rfq_id=deal.rfq_id).first()
        if demand_opp:
            if not DealOpportunityAttribution.objects.filter(
                deal=deal, opportunity=demand_opp, role="DEMAND_ORIGIN"
            ).exists():
                DealOpportunityAttribution.objects.create(
                    deal=deal,
                    opportunity=demand_opp,
                    role="DEMAND_ORIGIN",
                )
            if demand_opp.broker_id:
                if not DealBrokerAttribution.objects.filter(
                    deal=deal,
                    broker_organization_id=demand_opp.broker_id,
                    role="DEMAND_ORIGINATOR",
                    related_opportunity=demand_opp,
                ).exists():
                    DealBrokerAttribution.objects.create(
                        deal=deal,
                        broker_organization_id=demand_opp.broker_id,
                        role="DEMAND_ORIGINATOR",
                        related_opportunity=demand_opp,
                    )

        # Supply Opportunity from Offer
        offer = deal.offer
        supply_opp = offer.source_opportunity
        if supply_opp:
            if not DealOpportunityAttribution.objects.filter(
                deal=deal, opportunity=supply_opp, role="SUPPLY_ORIGIN"
            ).exists():
                DealOpportunityAttribution.objects.create(
                    deal=deal,
                    opportunity=supply_opp,
                    role="SUPPLY_ORIGIN",
                )
            if supply_opp.broker_id:
                if not DealBrokerAttribution.objects.filter(
                    deal=deal,
                    broker_organization_id=supply_opp.broker_id,
                    role="SUPPLY_ORIGINATOR",
                    related_opportunity=supply_opp,
                ).exists():
                    DealBrokerAttribution.objects.create(
                        deal=deal,
                        broker_organization_id=supply_opp.broker_id,
                        role="SUPPLY_ORIGINATOR",
                        related_opportunity=supply_opp,
                    )

        # Broker as offering party
        if offer.offeror_role == "BROKER" and offer.offering_organization_id:
            rel_opp = supply_opp
            if not DealBrokerAttribution.objects.filter(
                deal=deal,
                broker_organization_id=offer.offering_organization_id,
                role="SUPPLY_ORIGINATOR",
                related_opportunity=rel_opp,
            ).exists():
                DealBrokerAttribution.objects.create(
                    deal=deal,
                    broker_organization_id=offer.offering_organization_id,
                    role="SUPPLY_ORIGINATOR",
                    related_opportunity=rel_opp,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_dealattribution'),
        ('opportunities', '0010_opportunity_origin_area'),
        ('organizations', '0005_organizationoperatingarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealBrokerAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPPLY_ORIGINATOR', 'Supply Originator'), ('DEMAND_ORIGINATOR', 'Demand Originator')], help_text='Explicit broker originator role (SUPPLY_ORIGINATOR or DEMAND_ORIGINATOR).', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_organization', models.ForeignKey(help_text='Attributed Broker organization.', on_delete=django.db.models.deletion.PROTECT, related_name='deal_broker_attributions', to='organizations.organization')),
                ('deal', models.ForeignKey(help_text='Parent Deal aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='broker_attributions', to='deals.deal')),
                ('related_opportunity', models.ForeignKey(blank=True, help_text='Related source Opportunity if present in the provenance path.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_broker_attributions', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Deal Broker Attribution',
                'verbose_name_plural': 'Deal Broker Attributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal'], name='idx_deal_brk_deal'), models.Index(fields=['broker_organization'], name='idx_deal_brk_org'), models.Index(fields=['role'], name='idx_deal_brk_role'), models.Index(fields=['related_opportunity'], name='idx_deal_brk_opp'), models.Index(fields=['-created_at'], name='idx_deal_brk_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['SUPPLY_ORIGINATOR', 'DEMAND_ORIGINATOR'])), name='check_valid_deal_broker_role'), models.UniqueConstraint(fields=('deal', 'broker_organization', 'role', 'related_opportunity'), name='unique_deal_broker_role_opportunity', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='DealOpportunityAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('DEMAND_ORIGIN', 'Demand Origin'), ('SUPPLY_ORIGIN', 'Supply Origin')], help_text='Explicit opportunity provenance role (DEMAND_ORIGIN or SUPPLY_ORIGIN).', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(help_text='Parent Deal aggregate.', on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_attributions', to='deals.deal')),
                ('opportunity', models.ForeignKey(help_text='Source Opportunity lead in the trade origin path.', on_delete=django.db.models.deletion.PROTECT, related_name='deal_opportunity_attributions', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Deal Opportunity Attribution',
                'verbose_name_plural': 'Deal Opportunity Attributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal'], name='idx_deal_opp_deal'), models.Index(fields=['opportunity'], name='idx_deal_opp_opp'), models.Index(fields=['role'], name='idx_deal_opp_role'), models.Index(fields=['-created_at'], name='idx_deal_opp_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['DEMAND_ORIGIN', 'SUPPLY_ORIGIN'])), name='check_valid_deal_opportunity_role'), models.UniqueConstraint(fields=('deal', 'opportunity', 'role'), name='unique_deal_opportunity_role')],
            },
        ),
        migrations.RunPython(backfill_existing_deals_provenance, migrations.RunPython.noop),
    ]
