# Generated by Django 6.0.8 on 2026-09-14 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCounterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='Display or legal entity name of the external counterparty.', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Name of the individual representative or contact person.', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number for operational contact.', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email address for operational contact.', max_length=254)),
                ('geography', models.CharField(blank=True, help_text='Country, port, or regional jurisdiction.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Free-form operational notes by the Operator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who recorded this external counterparty (null if unassigned/system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_counterparties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Counterparty',
                'verbose_name_plural': 'External Counterparties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='idx_ext_cp_company_name'), models.Index(fields=['-created_at'], name='idx_ext_cp_created_at_desc')],
            },
        ),
    ]
