# Generated by Django 6.0.8 on 2026-09-14 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('organizations', '0004_organizationcommodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('Supply', 'Supply'), ('Demand', 'Demand')], help_text='Trade direction: Supply or Demand.', max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Lead quantity (must be positive if specified).', max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, default='MT', help_text='Unit of measurement.', max_length=20)),
                ('indicative_price', models.DecimalField(blank=True, decimal_places=2, help_text='Indicative or target unit price.', max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('delivery_window_start', models.DateField(blank=True, help_text='Earliest expected delivery date.', null=True)),
                ('delivery_window_end', models.DateField(blank=True, help_text='Latest expected delivery date.', null=True)),
                ('payment_terms', models.CharField(blank=True, help_text='Indicative payment terms.', max_length=255)),
                ('geography', models.CharField(blank=True, help_text='Origin/destination region, country, or port.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal operational notes.')),
                ('status', models.CharField(choices=[('Captured', 'Captured')], default='Captured', help_text='Foundational lifecycle state.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(blank=True, help_text='Referenced commodity definition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='commodities.commoditydefinition')),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who recorded this opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('external_counterparty', models.ForeignKey(blank=True, help_text='Off-platform external counterparty (mutually exclusive with organization).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.externalcounterparty')),
                ('organization', models.ForeignKey(blank=True, help_text='Internal registered platform organization (mutually exclusive with external_counterparty).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction'], name='idx_opp_direction'), models.Index(fields=['status'], name='idx_opp_status'), models.Index(fields=['organization'], name='idx_opp_organization'), models.Index(fields=['external_counterparty'], name='idx_opp_ext_counterparty'), models.Index(fields=['commodity'], name='idx_opp_commodity'), models.Index(fields=['-created_at'], name='idx_opp_created_at_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('direction__in', ['Supply', 'Demand'])), name='check_valid_opportunity_direction'), models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('external_counterparty__isnull', True)), models.Q(('organization__isnull', True), ('external_counterparty__isnull', False)), _connector='OR'), name='check_opportunity_counterparty_exclusive'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__isnull', True), _connector='OR'), name='check_positive_opportunity_quantity'), models.CheckConstraint(condition=models.Q(('indicative_price__gte', 0), ('indicative_price__isnull', True), _connector='OR'), name='check_non_negative_opportunity_indicative_price'), models.CheckConstraint(condition=models.Q(('status__in', ['Captured'])), name='check_valid_opportunity_status'), models.CheckConstraint(condition=models.Q(('delivery_window_end__gte', models.F('delivery_window_start')), ('delivery_window_start__isnull', True), ('delivery_window_end__isnull', True), _connector='OR'), name='check_valid_opportunity_delivery_window')],
            },
        ),
    ]
