# Generated by Django 6.0.8 on 2026-09-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('opportunities', '0003_opportunity_identifier'),
        ('organizations', '0004_organizationcommodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Attributed broker organization for broker referrals.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brokered_opportunities', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('broker_referral', 'Broker Referral'), ('operator_sourcing', 'Operator Sourcing'), ('buyer_referral', 'Buyer Referral'), ('supplier_referral', 'Supplier Referral'), ('existing_relationship', 'Existing Relationship'), ('inbound_lead', 'Inbound Lead')], default='operator_sourcing', help_text='Authoritative origin source of the opportunity lead.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['source'], name='idx_opp_source'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['broker'], name='idx_opp_broker'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['broker_referral', 'operator_sourcing', 'buyer_referral', 'supplier_referral', 'existing_relationship', 'inbound_lead'])), name='check_valid_opportunity_source'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'broker_referral'), ('broker__isnull', False)), models.Q(models.Q(('source', 'broker_referral'), _negated=True), ('broker__isnull', True)), _connector='OR'), name='check_opportunity_broker_source_consistency'),
        ),
    ]
