# Generated by Django 6.0.8 on 2026-09-15 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('opportunities', '0004_opportunity_source_and_broker'),
        ('organizations', '0004_organizationcommodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunity',
            name='check_valid_opportunity_status',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contacted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was marked as contacted.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was converted.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expiration_reason',
            field=models.TextField(blank=True, help_text='Operational reason or notes regarding expiration.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity expired.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='held_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was put on hold.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Operational reason provided when putting the opportunity on hold.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was marked lost.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.TextField(blank=True, help_text='Reason provided when marking the opportunity as lost.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='qualified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was qualified.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the opportunity was rejected.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided when rejecting the opportunity.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status_before_hold',
            field=models.CharField(blank=True, help_text='Persisted status prior to entering On Hold.', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='version',
            field=models.IntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('Captured', 'Captured'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Matching', 'Matching'), ('Converted', 'Converted'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('Lost', 'Lost'), ('Expired', 'Expired')], default='Captured', help_text='Foundational lifecycle state.', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Captured', 'Contacted', 'Qualified', 'Matching', 'Converted', 'On Hold', 'Rejected', 'Lost', 'Expired'])), name='check_valid_opportunity_status'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_opportunity_version'),
        ),
    ]
