# Generated by Django 6.0.8 on 2026-09-15 21:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunity_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityContactAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('MESSAGE', 'Message'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note')], help_text='Type of contact attempt: CALL, MESSAGE, EMAIL, MEETING, NOTE.', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the interaction took place (supports past interactions).')),
                ('notes', models.TextField(blank=True, default='', help_text='Operational notes or details regarding the interaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(help_text='Parent opportunity for this contact attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='opportunities.opportunity')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Operator who recorded this contact attempt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contact_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Contact Attempt',
                'verbose_name_plural': 'Opportunity Contact Attempts',
                'ordering': ['-occurred_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['opportunity', '-occurred_at', '-created_at'], name='idx_opp_cnt_opp_occ_desc'), models.Index(fields=['type'], name='idx_opp_cnt_type'), models.Index(fields=['-created_at'], name='idx_opp_cnt_created_at_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['CALL', 'MESSAGE', 'EMAIL', 'MEETING', 'NOTE'])), name='check_valid_contact_attempt_type')],
            },
        ),
    ]
