# Generated by Django 6.0.8 on 2026-09-15 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunitycontactattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief summary or action required for the follow-up task.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed instructions or operational context for the follow-up task.')),
                ('due_at', models.DateTimeField(help_text='Due date and time for the follow-up task.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Current lifecycle state of the task.', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task was marked as completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assigned internal Operator or Product Admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunity_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunity_tasks', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(help_text='Parent opportunity for this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Task',
                'verbose_name_plural': 'Opportunity Tasks',
                'ordering': ['due_at', 'created_at', 'id'],
                'indexes': [models.Index(fields=['opportunity', 'due_at', 'created_at'], name='idx_opp_tsk_opp_due_cr'), models.Index(fields=['status'], name='idx_opp_tsk_status'), models.Index(fields=['assigned_to'], name='idx_opp_tsk_assigned'), models.Index(fields=['due_at'], name='idx_opp_tsk_due_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'COMPLETED', 'CANCELLED'])), name='check_valid_opportunity_task_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), ('completed_at__isnull', False)), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='check_opportunity_task_completed_at_consistency')],
            },
        ),
    ]
