# Generated by Django 6.0.8 on 2026-09-15 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('opportunities', '0007_opportunitytask'),
        ('organizations', '0004_organizationcommodity'),
        ('trade_hub', '0003_supplylisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='converted_rfq',
            field=models.OneToOneField(blank=True, help_text='Authoritative RFQ created from this Opportunity upon conversion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_opportunity', to='trade_hub.rfq'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='schema_version',
            field=models.ForeignKey(blank=True, help_text='Optional exact commodity schema version if dynamic specifications were recorded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='commodities.commodityschemaversion'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic technical specifications validated against the referenced schema version.'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['converted_rfq'], name='idx_opp_converted_rfq'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['schema_version'], name='idx_opp_schema_version'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('converted_rfq__isnull', True), ('status', 'Converted'), _connector='OR'), name='check_rfq_only_when_converted'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'Demand'), ('status', 'Converted'), _negated=True), ('converted_rfq__isnull', False), _connector='OR'), name='check_demand_converted_has_rfq'),
        ),
    ]
