# Generated by Django 6.0.8 on 2026-09-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('opportunities', '0008_opportunity_conversion'),
        ('organizations', '0004_organizationcommodity'),
        ('trade_hub', '0003_supplylisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='converted_supply_listing',
            field=models.OneToOneField(blank=True, help_text='Authoritative Supply Listing created from this Opportunity upon conversion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_opportunity', to='trade_hub.supplylisting'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['converted_supply_listing'], name='idx_opp_converted_supply_listing'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('converted_supply_listing__isnull', True), ('status', 'Converted'), _connector='OR'), name='check_supply_listing_only_when_converted'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'Supply'), ('status', 'Converted'), _negated=True), ('converted_supply_listing__isnull', False), _connector='OR'), name='check_supply_converted_has_listing'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('converted_rfq__isnull', True), ('converted_supply_listing__isnull', True), _connector='OR'), name='check_no_dual_conversion_targets'),
        ),
    ]
