# Generated by Django 6.0.8 on 2026-09-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('opportunities', '0009_opportunity_supply_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='origin_area',
            field=models.ForeignKey(blank=True, help_text='Structured origin or supply geographic area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='geography.geographicarea'),
        ),
    ]
