# Generated by Django 6.0.8 on 2026-09-10 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommodityDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique canonical code (e.g., bitumen)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name_fa", models.CharField(help_text="Persian name", max_length=255)),
                ("name_en", models.CharField(help_text="English name", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommoditySchemaVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Version number (e.g., 1, 2)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_versions",
                        to="commodities.commoditydefinition",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commoditydefinition",
            name="active_schema_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The currently active schema version for new domain instances.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="commodities.commodityschemaversion",
            ),
        ),
        migrations.CreateModel(
            name="CommodityAttributeDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Canonical machine-readable key", max_length=100
                    ),
                ),
                (
                    "label_fa",
                    models.CharField(help_text="Persian label", max_length=255),
                ),
                (
                    "label_en",
                    models.CharField(help_text="English label", max_length=255),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("enum", "Enum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "unit_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unit metadata (e.g., canonical unit, allowed units)",
                    ),
                ),
                (
                    "enum_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enum metadata (canonical value, localized labels, sort order)",
                    ),
                ),
                (
                    "validation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules (e.g., min/max values, min/max length)",
                    ),
                ),
                (
                    "display_group",
                    models.CharField(
                        blank=True,
                        help_text="Logical group for UI presentation",
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Deterministic sort order"
                    ),
                ),
                (
                    "schema_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="commodities.commodityschemaversion",
                    ),
                ),
            ],
            options={
                "ordering": ["schema_version", "sort_order", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="commodityschemaversion",
            constraint=models.UniqueConstraint(
                fields=("commodity", "version"), name="unique_commodity_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="commodityschemaversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "retired"])),
                name="check_valid_schema_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="commodityattributedefinition",
            constraint=models.UniqueConstraint(
                fields=("schema_version", "key"), name="unique_schema_version_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="commodityattributedefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "data_type__in",
                        ["string", "number", "integer", "boolean", "enum"],
                    )
                ),
                name="check_valid_data_type",
            ),
        ),
    ]
