# Generated by Django 6.0.8 on 2026-09-17 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_semantic_identities(apps, schema_editor):
    CommodityAttributeDefinition = apps.get_model('commodities', 'CommodityAttributeDefinition')
    CommodityAttributeSemanticIdentity = apps.get_model('commodities', 'CommodityAttributeSemanticIdentity')

    # Known deterministic seed identities for bitumen and base_oil
    SEED_IDENTITIES = {
        # bitumen
        ("bitumen", "penetration_grade"): ("10000000-0000-0000-0000-000000000001", "penetration_grade", "درجه نفوذ", "Penetration Grade"),
        ("bitumen", "penetration"): ("10000000-0000-0000-0000-000000000002", "penetration", "نفوذپذیری", "Penetration"),
        ("bitumen", "softening_point"): ("10000000-0000-0000-0000-000000000003", "softening_point", "نقطه نرمی", "Softening Point"),
        ("bitumen", "ductility"): ("10000000-0000-0000-0000-000000000004", "ductility", "انگمی", "Ductility"),
        ("bitumen", "flash_point"): ("10000000-0000-0000-0000-000000000005", "flash_point", "نقطه اشتعال", "Flash Point"),
        ("bitumen", "solubility"): ("10000000-0000-0000-0000-000000000006", "solubility", "حلالیت", "Solubility"),
        ("bitumen", "loss_on_heating"): ("10000000-0000-0000-0000-000000000007", "loss_on_heating", "افت وزنی", "Loss on Heating"),
        # base_oil
        ("base_oil", "base_oil_group"): ("20000000-0000-0000-0000-000000000001", "base_oil_group", "گروه روغن پایه", "Base Oil Group"),
        ("base_oil", "viscosity_grade"): ("20000000-0000-0000-0000-000000000002", "viscosity_grade", "گرید گرانروی", "Viscosity Grade"),
        ("base_oil", "viscosity_at_40c"): ("20000000-0000-0000-0000-000000000003", "viscosity_at_40c", "گرانروی در ۴۰ درجه", "Viscosity at 40°C"),
        ("base_oil", "viscosity_index"): ("20000000-0000-0000-0000-000000000004", "viscosity_index", "شاخص گرانروی", "Viscosity Index"),
        ("base_oil", "flash_point"): ("20000000-0000-0000-0000-000000000005", "flash_point", "نقطه اشتعال", "Flash Point"),
        ("base_oil", "pour_point"): ("20000000-0000-0000-0000-000000000006", "pour_point", "نقطه ریزش", "Pour Point"),
    }

    attrs = CommodityAttributeDefinition.objects.filter(semantic_identity__isnull=True).select_related('schema_version__commodity')
    for attr in attrs:
        commodity = attr.schema_version.commodity
        key_tuple = (commodity.code, attr.key)
        if key_tuple in SEED_IDENTITIES:
            sid, code, n_fa, n_en = SEED_IDENTITIES[key_tuple]
            sem, _ = CommodityAttributeSemanticIdentity.objects.get_or_create(
                id=sid,
                commodity=commodity,
                defaults={
                    "code": code,
                    "name_fa": n_fa,
                    "name_en": n_en,
                }
            )
            attr.semantic_identity = sem
            attr.save(update_fields=['semantic_identity'])
        else:
            sem_id = uuid.uuid4()
            code = f"{attr.key}_{sem_id.hex[:8]}"
            sem = CommodityAttributeSemanticIdentity.objects.create(
                id=sem_id,
                commodity=commodity,
                code=code,
                name_fa=attr.label_fa,
                name_en=attr.label_en,
            )
            attr.semantic_identity = sem
            attr.save(update_fields=['semantic_identity'])


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAttributeSemanticIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Explicit canonical identifier for this semantic identity within the commodity.', max_length=100)),
                ('name_fa', models.CharField(blank=True, default='', help_text='Persian description of the semantic concept.', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', help_text='English description of the semantic concept.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional technical description of the semantic concept and measurement criteria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='The commodity definition this semantic identity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semantic_identities', to='commodities.commoditydefinition')),
            ],
            options={
                'ordering': ['commodity', 'code'],
            },
        ),
        migrations.AddField(
            model_name='commodityattributedefinition',
            name='semantic_identity',
            field=models.ForeignKey(blank=True, help_text='Explicit semantic identity for cross-schema matching.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='commodities.commodityattributesemanticidentity'),
        ),
        migrations.AddIndex(
            model_name='commodityattributesemanticidentity',
            index=models.Index(fields=['commodity', 'code'], name='idx_attr_semantic_id_code'),
        ),
        migrations.AddConstraint(
            model_name='commodityattributesemanticidentity',
            constraint=models.UniqueConstraint(fields=('commodity', 'code'), name='unique_commodity_semantic_identity_code'),
        ),
        migrations.RunPython(
            code=backfill_semantic_identities,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
