# Generated by Django 6.0.8 on 2026-09-13 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('organizations', '0004_organizationcommodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_operator', models.BooleanField(default=False, help_text='True if created by a platform operator on behalf of the buyer organization.')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Dynamic technical specifications validated against the referenced schema version.')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Procurement quantity (must be positive).', max_digits=15)),
                ('unit', models.CharField(default='MT', help_text='Unit of measurement (e.g. MT, Barrels).', max_length=20)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional target price per unit.', max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 3-letter currency code (e.g. USD, EUR).', max_length=3)),
                ('payment_terms', models.CharField(blank=True, help_text='Requested payment terms (e.g. LC, TT).', max_length=255)),
                ('incoterm', models.CharField(blank=True, help_text='Incoterm code (e.g. FOB, CIF, CFR).', max_length=10)),
                ('origin', models.CharField(blank=True, help_text='Requested origin country or port.', max_length=255)),
                ('destination', models.CharField(blank=True, help_text='Requested destination country or port.', max_length=255)),
                ('delivery_window_start', models.DateField(blank=True, help_text='Earliest acceptable delivery date.', null=True)),
                ('delivery_window_end', models.DateField(blank=True, help_text='Latest acceptable delivery date.', null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, help_text='Offer submission deadline.', null=True)),
                ('inspection_required', models.BooleanField(default=False, help_text='Whether third-party quality inspection is required.')),
                ('quality_notes', models.TextField(blank=True, help_text='Quality, testing, or inspection instructions.')),
                ('notes', models.TextField(blank=True, help_text='General procurement notes or comments.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('collecting_offers', 'Collecting Offers'), ('negotiating', 'Negotiating'), ('awarded', 'Awarded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current lifecycle state of the RFQ.', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('network', 'Network'), ('private', 'Private')], default='private', help_text='Participation visibility tier (private, network, public).', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when the RFQ was published.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the RFQ was closed.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the RFQ was cancelled.', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason provided when the RFQ was cancelled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Referenced commodity definition.', on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='commodities.commoditydefinition')),
                ('created_by', models.ForeignKey(blank=True, help_text='The authenticated user who created this RFQ.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The buyer organization that owns this RFQ.', on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='organizations.organization')),
                ('schema_version', models.ForeignKey(help_text='Exact immutable commodity schema version used to validate dynamic specifications.', on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='commodities.commodityschemaversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='idx_rfq_organization'), models.Index(fields=['commodity'], name='idx_rfq_commodity'), models.Index(fields=['status', 'visibility'], name='idx_rfq_status_visibility'), models.Index(fields=['-created_at'], name='idx_rfq_created_at_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'collecting_offers', 'negotiating', 'awarded', 'closed', 'cancelled'])), name='check_valid_rfq_status'), models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'network', 'private'])), name='check_valid_rfq_visibility'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_positive_rfq_quantity'), models.CheckConstraint(condition=models.Q(('target_price__gte', 0), ('target_price__isnull', True), _connector='OR'), name='check_positive_rfq_target_price'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_rfq_version'), models.CheckConstraint(condition=models.Q(('delivery_window_end__gte', models.F('delivery_window_start')), ('delivery_window_start__isnull', True), ('delivery_window_end__isnull', True), _connector='OR'), name='check_valid_rfq_delivery_window')],
            },
        ),
    ]
