# Generated by Django 6.0.8 on 2026-09-13 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organizationcommodity"),
        ("trade_hub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("viewed", "Viewed"),
                            ("responded", "Responded"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="invited",
                        help_text="Current lifecycle state of the invitation.",
                        max_length=30,
                    ),
                ),
                (
                    "invited_by_operator",
                    models.BooleanField(
                        default=False,
                        help_text="True if invited by a platform operator on behalf of the buyer organization.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the invitee first viewed the RFQ/invitation.",
                        null=True,
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the invitee submitted a response or offer.",
                        null=True,
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the invitee declined the invitation.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the invitation expires.",
                        null=True,
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason provided when declining the invitation.",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authenticated user who sent the invitation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_rfq_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The invited supplier or broker organization.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_invitations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        help_text="The RFQ to which the organization is invited.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="trade_hub.rfq",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="idx_rfq_inv_org_status"
                    ),
                    models.Index(
                        fields=["rfq", "status"], name="idx_rfq_inv_rfq_status"
                    ),
                    models.Index(
                        fields=["-created_at"], name="idx_rfq_inv_created_at_desc"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rfq", "organization"),
                        name="unique_rfq_organization_invitation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "invited",
                                    "viewed",
                                    "responded",
                                    "declined",
                                    "expired",
                                ],
                            )
                        ),
                        name="check_valid_rfq_invitation_status",
                    ),
                ],
            },
        ),
    ]
