# Generated by Django 6.0.8 on 2026-09-13 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('organizations', '0004_organizationcommodity'),
        ('trade_hub', '0002_rfqinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_operator', models.BooleanField(default=False, help_text='True if created by a platform operator on behalf of the supplier organization.')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Dynamic technical specifications validated against the referenced schema version.')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Supply quantity available (must be positive).', max_digits=15)),
                ('unit', models.CharField(default='MT', help_text='Unit of measurement (e.g. MT, Barrels).', max_length=20)),
                ('indicative_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional indicative price per unit.', max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 3-letter currency code (e.g. USD, EUR).', max_length=3)),
                ('payment_terms', models.CharField(blank=True, help_text='Indicative payment terms (e.g. LC, TT).', max_length=255)),
                ('incoterm', models.CharField(blank=True, help_text='Incoterm code (e.g. FOB, CIF, CFR).', max_length=10)),
                ('origin', models.CharField(blank=True, help_text='Origin location, facility, or port.', max_length=255)),
                ('destination', models.CharField(blank=True, help_text='Allowable destination country or port if restricted.', max_length=255)),
                ('availability_window_start', models.DateField(blank=True, help_text='Earliest availability date.', null=True)),
                ('availability_window_end', models.DateField(blank=True, help_text='Latest availability date.', null=True)),
                ('quality_notes', models.TextField(blank=True, help_text='Quality, testing, or specification notes.')),
                ('notes', models.TextField(blank=True, help_text='General internal notes or comments (hidden from external counterparties).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], default='draft', help_text='Current lifecycle state of the supply listing.', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('network', 'Network'), ('private', 'Private')], default='public', help_text='Participation visibility tier (public, network, private).', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Timestamp when the supply listing was activated.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the supply listing was closed.', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Timestamp when the supply listing was marked expired.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Referenced commodity definition.', on_delete=django.db.models.deletion.PROTECT, related_name='supply_listings', to='commodities.commoditydefinition')),
                ('created_by', models.ForeignKey(blank=True, help_text='The authenticated user who created this supply listing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_supply_listings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The supplier organization that owns this supply listing.', on_delete=django.db.models.deletion.PROTECT, related_name='supply_listings', to='organizations.organization')),
                ('schema_version', models.ForeignKey(help_text='Exact immutable commodity schema version used to validate dynamic specifications.', on_delete=django.db.models.deletion.PROTECT, related_name='supply_listings', to='commodities.commodityschemaversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='idx_supply_organization'), models.Index(fields=['commodity'], name='idx_supply_commodity'), models.Index(fields=['status', 'visibility'], name='idx_supply_status_visibility'), models.Index(fields=['-created_at'], name='idx_supply_created_at_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'expired', 'closed'])), name='check_valid_supply_listing_status'), models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'network', 'private'])), name='check_valid_supply_listing_visibility'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_positive_supply_listing_quantity'), models.CheckConstraint(condition=models.Q(('indicative_price__gte', 0), ('indicative_price__isnull', True), _connector='OR'), name='check_positive_supply_listing_price'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_supply_listing_version'), models.CheckConstraint(condition=models.Q(('availability_window_end__gte', models.F('availability_window_start')), ('availability_window_start__isnull', True), ('availability_window_end__isnull', True), _connector='OR'), name='check_valid_supply_listing_availability_window')],
            },
        ),
    ]
