# Generated by Django 6.0.8 on 2026-09-17 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('trade_hub', '0003_supplylisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='destination_area',
            field=models.ForeignKey(blank=True, help_text='Structured destination geographic area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_as_destination', to='geography.geographicarea'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='origin_area',
            field=models.ForeignKey(blank=True, help_text='Structured origin geographic area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_as_origin', to='geography.geographicarea'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='origin_area',
            field=models.ForeignKey(blank=True, help_text='Structured origin or supply geographic area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_listings', to='geography.geographicarea'),
        ),
        migrations.CreateModel(
            name='RFQGeographyConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('REQUIRED', 'Required'), ('ALLOWED', 'Allowed'), ('PREFERRED', 'Preferred'), ('EXCLUDED', 'Excluded')], default='REQUIRED', help_text='Constraint mode: REQUIRED, ALLOWED, PREFERRED, or EXCLUDED.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(help_text='Referenced geographic area.', on_delete=django.db.models.deletion.CASCADE, related_name='rfq_constraints', to='geography.geographicarea')),
                ('rfq', models.ForeignKey(help_text='Target RFQ.', on_delete=django.db.models.deletion.CASCADE, related_name='geography_constraints', to='trade_hub.rfq')),
            ],
            options={
                'indexes': [models.Index(fields=['rfq', 'mode'], name='idx_rfq_geo_mode')],
                'constraints': [models.UniqueConstraint(fields=('rfq', 'mode', 'area'), name='unique_rfq_geography_constraint')],
            },
        ),
    ]
