# Generated by Django 6.0.8 on 2026-09-23 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionMilestoneDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Canonical uppercase machine code (e.g. AWARDED, LOADING_SCHEDULED)', max_length=100)),
                ('name_fa', models.CharField(help_text='Persian display label', max_length=255)),
                ('name_en', models.CharField(help_text='English display label', max_length=255)),
                ('sort_order', models.PositiveIntegerField(help_text='Deterministic display and logical order within the version')),
                ('required', models.BooleanField(default=True, help_text='Whether this milestone is required for workflow completion')),
                ('blocking', models.BooleanField(default=False, help_text='Whether downstream milestones are blocked until this milestone is completed')),
                ('terminal', models.BooleanField(default=False, help_text='Whether completing this milestone marks the execution as CLOSED')),
                ('expected_offset_days', models.PositiveIntegerField(blank=True, help_text='Default expected offset days from execution start', null=True)),
                ('category', models.CharField(blank=True, default='', help_text='Optional category (e.g. COMMERCIAL, LOGISTICS, QUALITY, PAYMENT, CLOSURE)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['workflow_template_version', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionWorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Canonical lowercase machine code (e.g. bitumen_standard)', max_length=100, unique=True)),
                ('name_fa', models.CharField(help_text='Persian name', max_length=255)),
                ('name_en', models.CharField(help_text='English name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed workflow description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active for new executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionMilestoneDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(help_text='The milestone that requires the prerequisite', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_dependencies', to='execution.executionmilestonedefinition')),
                ('prerequisite', models.ForeignKey(help_text='The prerequisite milestone that must precede', on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='execution.executionmilestonedefinition')),
            ],
        ),
        migrations.AddField(
            model_name='executionmilestonedefinition',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Prerequisite milestones that must be completed before this milestone', related_name='downstream_milestones', through='execution.ExecutionMilestoneDependency', through_fields=('milestone', 'prerequisite'), to='execution.executionmilestonedefinition'),
        ),
        migrations.CreateModel(
            name='ExecutionWorkflowTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Monotonically increasing version number within the template')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=20)),
                ('change_summary', models.TextField(blank=True, default='', help_text='Summary of changes in this version')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Internal user who created this draft version', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Parent workflow template', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='execution.executionworkflowtemplate')),
            ],
            options={
                'ordering': ['template', 'version_number'],
            },
        ),
        migrations.AddField(
            model_name='executionworkflowtemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='The currently active published version for new execution instances.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='execution.executionworkflowtemplateversion'),
        ),
        migrations.AddField(
            model_name='executionmilestonedefinition',
            name='workflow_template_version',
            field=models.ForeignKey(help_text='Parent workflow template version', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='execution.executionworkflowtemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestonedependency',
            constraint=models.UniqueConstraint(fields=('milestone', 'prerequisite'), name='unique_milestone_dependency'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestonedependency',
            constraint=models.CheckConstraint(condition=models.Q(('milestone', models.F('prerequisite')), _negated=True), name='check_no_self_dependency'),
        ),
        migrations.AddConstraint(
            model_name='executionworkflowtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_workflow_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='executionworkflowtemplateversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'RETIRED'])), name='check_valid_workflow_version_status'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestonedefinition',
            constraint=models.UniqueConstraint(fields=('workflow_template_version', 'code'), name='unique_version_milestone_code'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestonedefinition',
            constraint=models.UniqueConstraint(fields=('workflow_template_version', 'sort_order'), name='unique_version_milestone_sort_order'),
        ),
    ]
