# Generated by Django 6.0.8 on 2026-09-23 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealbrokerattribution_dealopportunityattribution'),
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', help_text='Execution operational lifecycle status (OPEN or CLOSED).', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when execution monitoring started.')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when execution reached CLOSED status.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(help_text='Authoritative source Deal aggregate (1 Deal -> exactly 1 Execution).', on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='deals.deal')),
                ('workflow_template_version', models.ForeignKey(help_text='Immutable workflow template version bound at creation time.', on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='execution.executionworkflowtemplateversion')),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', help_text='Runtime status of this milestone instance.', max_length=20)),
                ('expected_at', models.DateTimeField(blank=True, help_text='Target expected completion date/time.', null=True)),
                ('actual_at', models.DateTimeField(blank=True, help_text='Actual historical occurrence timestamp.', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when milestone completion was recorded.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational notes or transition reasons.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who authoritatively recorded completion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(help_text='Milestone definition from the bound workflow template version.', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='execution.executionmilestonedefinition')),
                ('execution', models.ForeignKey(help_text='Parent execution instance.', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='execution.execution')),
            ],
            options={
                'verbose_name': 'Execution Milestone',
                'verbose_name_plural': 'Execution Milestones',
                'ordering': ['execution', 'definition__sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['status', '-created_at'], name='idx_exec_status_created'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('deal',), name='unique_execution_deal'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='check_valid_execution_status'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_execution_version'),
        ),
        migrations.AddIndex(
            model_name='executionmilestone',
            index=models.Index(fields=['execution', 'status'], name='idx_exec_milestone_status'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestone',
            constraint=models.UniqueConstraint(fields=('execution', 'definition'), name='unique_execution_milestone_definition'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'SKIPPED'])), name='check_valid_milestone_status'),
        ),
        migrations.AddConstraint(
            model_name='executionmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_milestone_version'),
        ),
    ]
