# Generated by Django 6.0.8 on 2026-09-23 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_execution_executionmilestone_and_more'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLogistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(blank=True, default='', help_text='Carrier name or operational freight operator.', max_length=255)),
                ('transport_mode', models.CharField(blank=True, choices=[('ROAD', 'Road'), ('SEA', 'Sea'), ('RAIL', 'Rail'), ('AIR', 'Air'), ('MULTIMODAL', 'Multimodal'), ('OTHER', 'Other')], default=None, help_text='Canonical transport mode. Must not be inferred automatically.', max_length=20, null=True)),
                ('pickup_location', models.CharField(blank=True, default='', help_text='Operational pickup facility description or local address.', max_length=255)),
                ('destination_location', models.CharField(blank=True, default='', help_text='Operational destination facility description or local address.', max_length=255)),
                ('scheduled_loading_at', models.DateTimeField(blank=True, help_text='Scheduled operational loading timestamp.', null=True)),
                ('actual_loading_at', models.DateTimeField(blank=True, help_text='Reported actual operational loading timestamp.', null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='Estimated time of arrival (ETA) at destination.', null=True)),
                ('actual_delivery_at', models.DateTimeField(blank=True, help_text='Reported actual operational delivery timestamp.', null=True)),
                ('transport_reference', models.CharField(blank=True, default='', help_text='Operational transport reference (e.g. B/L, CMR, tracking number).', max_length=255)),
                ('logistics_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual or reported operational logistics cost in Decimal.', max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='', help_text='ISO 4217 3-letter currency code for logistics cost.', max_length=3)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_area', models.ForeignKey(blank=True, help_text='Structured destination geographic area reference.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.geographicarea')),
                ('execution', models.OneToOneField(help_text='Parent execution instance (1 Execution -> max 1 ExecutionLogistics).', on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='execution.execution')),
                ('pickup_area', models.ForeignKey(blank=True, help_text='Structured pickup geographic area reference.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.geographicarea')),
            ],
            options={
                'verbose_name': 'Execution Logistics',
                'verbose_name_plural': 'Execution Logistics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='idx_exec_logistics_created')],
                'constraints': [models.UniqueConstraint(fields=('execution',), name='unique_execution_logistics'), models.CheckConstraint(condition=models.Q(('transport_mode__isnull', True), ('transport_mode__in', ['ROAD', 'SEA', 'RAIL', 'AIR', 'MULTIMODAL', 'OTHER']), _connector='OR'), name='check_valid_transport_mode'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_logistics_version'), models.CheckConstraint(condition=models.Q(('logistics_cost__isnull', True), ('logistics_cost__gte', 0), _connector='OR'), name='check_non_negative_logistics_cost')],
            },
        ),
    ]
