# Generated by Django 6.0.8 on 2026-09-23 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_executionlogistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=False, help_text='Whether quality inspection is required by commercial context.')),
                ('agency', models.CharField(blank=True, default='', help_text='Inspection agency or organization name (e.g. SGS, Bureau Veritas).', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled inspection timestamp.', null=True)),
                ('inspection_at', models.DateTimeField(blank=True, help_text='Authoritative historical inspection occurrence timestamp.', null=True)),
                ('status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Runtime status of this inspection record.', max_length=20)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL', 'Conditional'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Authoritative quality inspection result (PASS, FAIL, CONDITIONAL, UNKNOWN).', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational notes or instructions. Must never be used to infer result or status.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.OneToOneField(help_text='Parent execution instance (1 Execution -> max 1 ExecutionInspection).', on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='execution.execution')),
            ],
            options={
                'verbose_name': 'Execution Inspection',
                'verbose_name_plural': 'Execution Inspections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='idx_exec_inspection_created'), models.Index(fields=['execution', 'status'], name='idx_exec_inspection_status')],
                'constraints': [models.UniqueConstraint(fields=('execution',), name='unique_execution_inspection'), models.CheckConstraint(condition=models.Q(('status__in', ['NOT_REQUIRED', 'PENDING', 'SCHEDULED', 'COMPLETED', 'CANCELLED'])), name='check_valid_inspection_status'), models.CheckConstraint(condition=models.Q(('result__in', ['PASS', 'FAIL', 'CONDITIONAL', 'UNKNOWN'])), name='check_valid_inspection_result'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_inspection_version')],
            },
        ),
    ]
