# Generated by Django 6.0.8 on 2026-09-23 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_executioninspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('REPORTED', 'Reported'), ('CONFIRMED', 'Confirmed')], db_index=True, default='EXPECTED', help_text='Runtime status of this payment monitoring record (EXPECTED, REPORTED, CONFIRMED).', max_length=20)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Authoritative expected payment amount derived from immutable Deal commercial truth.', max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', help_text='ISO 4217 3-letter currency code from Deal commercial snapshot.', max_length=3)),
                ('expected_at', models.DateTimeField(blank=True, help_text='Expected payment due date/time if deterministically supported.', null=True)),
                ('reported_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when payment was reported.', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when payment was confirmed by Operator/Admin.', null=True)),
                ('reference', models.CharField(blank=True, default='', help_text='Operational transaction/banking reference. Operational metadata only; never stores secrets.', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational notes. Notes do not determine payment status.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency aggregate version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Platform Operator/Admin user who authoritatively confirmed the payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('execution', models.OneToOneField(help_text='Parent execution instance (1 Execution -> max 1 ExecutionPayment).', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='execution.execution')),
                ('reported_by', models.ForeignKey(blank=True, help_text='Platform user who reported the payment fact.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Payment',
                'verbose_name_plural': 'Execution Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='idx_exec_payment_created'), models.Index(fields=['execution', 'status'], name='idx_exec_payment_status')],
                'constraints': [models.UniqueConstraint(fields=('execution',), name='unique_execution_payment'), models.CheckConstraint(condition=models.Q(('status__in', ['EXPECTED', 'REPORTED', 'CONFIRMED'])), name='check_valid_payment_status'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_positive_payment_version'), models.CheckConstraint(condition=models.Q(('expected_amount__gte', 0), ('expected_amount__isnull', True), _connector='OR'), name='check_positive_payment_expected_amount'), models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('reported_at__isnull', True), ('reported_by__isnull', True), ('status', 'EXPECTED')), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('reported_at__isnull', False), ('reported_by__isnull', False), ('status', 'REPORTED')), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('reported_at__isnull', False), ('reported_by__isnull', False), ('status', 'CONFIRMED')), _connector='OR'), name='check_payment_status_metadata_integrity')],
            },
        ),
    ]
