# Generated by Django 6.0.8 on 2026-09-23 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_executionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('PAYMENT_PROOF', 'Payment Proof'), ('LOADING_DOCUMENT', 'Loading Document'), ('INSPECTION_REPORT', 'Inspection Report'), ('TRANSPORT_DOCUMENT', 'Transport Document'), ('DELIVERY_PROOF', 'Delivery Proof'), ('ACCEPTANCE_DOCUMENT', 'Acceptance Document'), ('OTHER', 'Other')], db_index=True, help_text='Authoritative operational document category.', max_length=50)),
                ('file_name', models.CharField(help_text='Safe original filename.', max_length=255)),
                ('content_type', models.CharField(help_text='MIME content type.', max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField(help_text='File size in bytes.')),
                ('object_key', models.CharField(help_text='Internal storage object key in MinIO/S3. Never exposed to customer API.', max_length=1024, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Authoritative server timestamp when document was uploaded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(help_text='Parent execution instance.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='execution.execution')),
                ('inspection', models.ForeignKey(blank=True, help_text='Optional associated execution inspection instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='execution.executioninspection')),
                ('milestone', models.ForeignKey(blank=True, help_text='Optional associated execution milestone instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='execution.executionmilestone')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_execution_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Document',
                'verbose_name_plural': 'Execution Documents',
                'ordering': ['-uploaded_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['CONTRACT', 'PAYMENT_PROOF', 'LOADING_DOCUMENT', 'INSPECTION_REPORT', 'TRANSPORT_DOCUMENT', 'DELIVERY_PROOF', 'ACCEPTANCE_DOCUMENT', 'OTHER'])), name='check_valid_execution_document_category'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='check_positive_execution_document_size')],
            },
        ),
    ]
