# Generated by Django 6.0.8 on 2026-09-23 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_executiondocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('QUALITY', 'Quality'), ('QUANTITY', 'Quantity'), ('LOGISTICS', 'Logistics'), ('PAYMENT', 'Payment'), ('DOCUMENT', 'Document'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], db_index=True, help_text='Exact operational issue category.', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', help_text='Lifecycle status: OPEN, IN_PROGRESS, RESOLVED, CANCELLED.', max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Optional severity: LOW, MEDIUM, HIGH, CRITICAL.', max_length=50, null=True)),
                ('title', models.CharField(help_text='Concise title summarizing the operational issue.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed operational description or context.')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Authoritative server timestamp when issue was opened.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Authoritative server timestamp when issue was marked RESOLVED.', null=True)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Detailed notes explaining the resolution.')),
                ('blocks_execution', models.BooleanField(db_index=True, default=False, help_text='Whether this issue explicitly prevents execution closure while active.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency control version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(help_text='Parent execution instance.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='execution.execution')),
                ('opened_by', models.ForeignKey(blank=True, help_text='User who reported/opened this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_execution_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who authoritatively resolved this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_execution_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Issue',
                'verbose_name_plural': 'Execution Issues',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='executiondocument',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Optional associated execution issue instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='execution.executionissue'),
        ),
        migrations.AddConstraint(
            model_name='executionissue',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['QUALITY', 'QUANTITY', 'LOGISTICS', 'PAYMENT', 'DOCUMENT', 'CONTRACT', 'OTHER'])), name='check_valid_execution_issue_type'),
        ),
        migrations.AddConstraint(
            model_name='executionissue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED'])), name='check_valid_execution_issue_status'),
        ),
        migrations.AddConstraint(
            model_name='executionissue',
            constraint=models.CheckConstraint(condition=models.Q(('severity__isnull', True), ('severity__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']), _connector='OR'), name='check_valid_execution_issue_severity'),
        ),
        migrations.AddConstraint(
            model_name='executionissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), ('resolved_at__isnull', False)), models.Q(('status', 'RESOLVED'), _negated=True), _connector='OR'), name='check_resolved_issue_has_resolved_at'),
        ),
        migrations.AddConstraint(
            model_name='executionissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['OPEN', 'IN_PROGRESS']), _negated=True), models.Q(('status__in', ['OPEN', 'IN_PROGRESS']), ('resolved_at__isnull', True), ('resolved_by__isnull', True)), _connector='OR'), name='check_unresolved_issue_has_no_resolution_metadata'),
        ),
    ]
